import type { Metadata } from "next";

import { FourPillarsDiagram, GuideFigure } from "@/components/GuideFigure";
import {
  GuideNote,
  GuideSection,
  GuideShell,
  GuideTable,
} from "@/components/GuideShell";
import { BRANCH_RELATION_SCORE } from "@/lib/engines/branches";
import { SAJU_WEIGHTS } from "@/lib/engines/saju";
import { guideContext, guideMetadata, type GuidePageProps } from "@/lib/guide-page";
import { localePath } from "@/lib/locale-path";

const SLUG = "how-it-works";

export function generateMetadata(props: GuidePageProps): Promise<Metadata> {
  return guideMetadata(SLUG, props);
}

const percent = (value: number) => `${Math.round(value * 100)}%`;

export default async function Page(props: GuidePageProps) {
  const { locale, entry, hubHref } = await guideContext(SLUG, props);

  return (
    <GuideShell
      locale={locale}
      eyebrow={entry.eyebrow}
      title={entry.title}
      description={entry.summary}
      backHref={hubHref}
      backLabel="How this works"
    >
      <GuideSection title="Four pillars, eight characters">
        <p>
          Saju writes the year, month, day and hour of your birth as <b>four pillars</b>, each
          made of two characters — a heavenly stem above and an earthly branch below. Eight
          characters in all. That set is your natal chart.
        </p>
        <p>
          One of the eight matters more than the rest. The <b>stem of the day pillar</b> stands
          for you; it is called the <b>day master</b>. Almost everything this service shows is
          measured from that single character — the other seven describe the conditions it sits in.
        </p>
        <GuideNote title="The year turns at a solar term, not on 1 January">
          A Saju year begins at <i>ipchun</i>, around 4 February. If you were born in January or
          early February, your year pillar — and so your zodiac animal — belongs to the previous
          year. Entering a lunar date changes nothing about this: we convert it to a solar date
          first and then cut by solar terms.
        </GuideNote>
      </GuideSection>

      <GuideSection title="What we read from the chart">
        <GuideFigure caption="A Saju chart is the year, month, day and hour of birth, each written as two characters — a heavenly stem and an earthly branch. The day stem, highlighted here, is the character that stands for you.">
          <FourPillarsDiagram language="en" />
        </GuideFigure>
        <p>
          Every stem and branch belongs to one of the <b>five elements</b> — wood, fire, earth,
          metal and water. Counting them across the chart shows which energy runs thick and which
          runs thin. We do not simply count characters: the month of birth pushes some elements up
          and holds others down, and that seasonal standing is applied first.
        </p>
        <p>
          From those weights we judge whether the day master is <b>strong or weak</b>, and from
          that, which energy it needs now. That last value is what the daily reading leans on
          most.
        </p>
      </GuideSection>


      <GuideSection title="The branch relation table">
        <p>
          The branch of the current day is laid against each branch in your chart and judged with
          this table. These are the actual numbers the service uses.
        </p>
        <GuideTable
          head={["Relation", "Meaning", "Score"]}
          rows={[
            ["Samhap", "Three branches forming a complete bureau", BRANCH_RELATION_SCORE.SAMHAP],
            ["Yukhap", "A pair that draws together", BRANCH_RELATION_SCORE.YUKHAP],
            ["Banhap", "Half of a bureau, including its leading branch", BRANCH_RELATION_SCORE.BANHAP],
            ["Same branch", "Alike, but not drawn together", BRANCH_RELATION_SCORE.SAME],
            ["Neutral", "No named relation", BRANCH_RELATION_SCORE.NEUTRAL],
            ["Wonjin", "Quiet, lasting friction", BRANCH_RELATION_SCORE.WONJIN],
            ["Chung", "A head-on clash", BRANCH_RELATION_SCORE.CHUNG],
          ]}
        />
        <p>
          Note that the floor is {BRANCH_RELATION_SCORE.CHUNG}, not zero. In this tradition a
          clash is a collision, not an ending. Scoring it near zero would let the service
          pronounce a verdict on a relationship, which is not what it is for.
        </p>
      </GuideSection>

      <GuideSection title="Rules only — no AI, no randomness">
        <p>
          Every number above is a rule. Nothing is generated by a language model and nothing is
          random, so the same two birth dates always produce the same result. Since we store
          nothing, that determinism is what stands in for a saved record.
        </p>
        <p>
          When we change a scoring rule we raise the engine version, which is printed under
          your result. That tells you which set of rules produced the number you are looking at.
        </p>
      </GuideSection>

      <GuideSection title="Birth time and birth place">
        <p>
          The birth time is optional. Without it we leave out the hour pillar and mark the
          result accordingly. If you do know it, please also pick the city — clock time and
          solar time differ by up to half an hour, and the hour pillar changes in two-hour
          steps, so people born near a boundary land in the wrong pillar without the correction.
        </p>
      </GuideSection>

      <GuideSection title="What this is not">
        <p>
          This is a reading offered from the perspective of a traditional East Asian system. It
          is not a scientific prediction, and it is not a verdict on any relationship. Read it
          as one angle on two people, not as an answer.
        </p>
        <p>
          For what happens to the dates you type, see{" "}
          <a
            href={localePath("/guide/what-we-store", locale)}
            className="font-semibold text-brand-navy underline underline-offset-2"
          >
            what we store
          </a>
          .
        </p>
      </GuideSection>
    </GuideShell>
  );
}
