create table if not exists public.official_hanja_sources (
  id uuid primary key default gen_random_uuid(),
  source_key text not null unique,
  title text not null,
  publisher text,
  rule_reference text,
  version_label text,
  effective_date date,
  source_url text,
  source_file_name text,
  source_file_path text,
  source_sha256 text,
  status text not null default 'draft' check (
    status in ('draft', 'reviewed', 'production', 'archived')
  ),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.official_hanja_rules (
  id uuid primary key default gen_random_uuid(),
  source_id uuid not null references public.official_hanja_sources(id) on delete cascade,
  rule_code text not null,
  description text not null,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique (source_id, rule_code)
);

create table if not exists public.official_hanja_entries (
  id uuid primary key default gen_random_uuid(),
  source_id uuid not null references public.official_hanja_sources(id) on delete cascade,
  hangul_syllable text not null,
  hanja text not null,
  designated_reading text not null,
  meaning_ko text,
  table_section text not null default 'official_table',
  page_number integer,
  stroke_count integer,
  radical text,
  is_name_usable boolean not null default true,
  review_status text not null default 'ocr' check (
    review_status in ('draft', 'ocr', 'reviewed', 'production', 'rejected', 'sample')
  ),
  notes text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source_id, hangul_syllable, hanja, designated_reading, table_section)
);

create table if not exists public.official_hanja_variants (
  id uuid primary key default gen_random_uuid(),
  source_id uuid not null references public.official_hanja_sources(id) on delete cascade,
  base_hanja text not null,
  variant_hanja text not null,
  variant_type text not null default 'other' check (
    variant_type in ('same_character', 'popular_form', 'abbreviation', 'radical', 'other')
  ),
  rule_code text,
  notes text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (source_id, base_hanja, variant_hanja, variant_type)
);

create table if not exists public.official_pronunciation_sources (
  id uuid primary key default gen_random_uuid(),
  source_key text not null unique,
  title text not null,
  publisher text,
  source_url text,
  source_file_name text,
  source_file_path text,
  source_sha256 text,
  page_count integer,
  extraction_status text not null default 'pending' check (
    extraction_status in ('pending', 'needs_ocr', 'extracted', 'reviewed', 'production', 'archived')
  ),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.official_pronunciation_chunks (
  id bigint generated by default as identity primary key,
  source_id uuid not null references public.official_pronunciation_sources(id) on delete cascade,
  page_number integer not null,
  section_title text,
  content text not null,
  review_status text not null default 'ocr' check (
    review_status in ('ocr', 'reviewed', 'production', 'rejected')
  ),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.official_pronunciation_entries (
  id uuid primary key default gen_random_uuid(),
  source_id uuid not null references public.official_pronunciation_sources(id) on delete cascade,
  hangul text not null,
  romanization text not null,
  surname_usable boolean,
  given_name_usable boolean,
  page_number integer,
  review_status text not null default 'ocr' check (
    review_status in ('ocr', 'reviewed', 'production', 'rejected')
  ),
  notes text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source_id, hangul, romanization)
);

create index if not exists official_hanja_sources_status_idx
  on public.official_hanja_sources (status, effective_date desc);
create index if not exists official_hanja_entries_lookup_idx
  on public.official_hanja_entries (hangul_syllable, designated_reading, review_status);
create index if not exists official_hanja_entries_source_review_idx
  on public.official_hanja_entries (source_id, review_status, hangul_syllable);
create index if not exists official_hanja_entries_hanja_idx
  on public.official_hanja_entries (hanja);
create index if not exists official_hanja_variants_lookup_idx
  on public.official_hanja_variants (base_hanja, variant_hanja);
create index if not exists official_pronunciation_chunks_source_page_idx
  on public.official_pronunciation_chunks (source_id, review_status, page_number);
create index if not exists official_pronunciation_entries_lookup_idx
  on public.official_pronunciation_entries (romanization, review_status, hangul);
create index if not exists official_pronunciation_entries_source_idx
  on public.official_pronunciation_entries (source_id, review_status, page_number);

alter table public.official_hanja_sources enable row level security;
alter table public.official_hanja_rules enable row level security;
alter table public.official_hanja_entries enable row level security;
alter table public.official_hanja_variants enable row level security;
alter table public.official_pronunciation_sources enable row level security;
alter table public.official_pronunciation_chunks enable row level security;
alter table public.official_pronunciation_entries enable row level security;

revoke all on public.official_hanja_sources from anon, authenticated;
revoke all on public.official_hanja_rules from anon, authenticated;
revoke all on public.official_hanja_entries from anon, authenticated;
revoke all on public.official_hanja_variants from anon, authenticated;
revoke all on public.official_pronunciation_sources from anon, authenticated;
revoke all on public.official_pronunciation_chunks from anon, authenticated;
revoke all on public.official_pronunciation_entries from anon, authenticated;
grant all on public.official_hanja_sources to service_role;
grant all on public.official_hanja_rules to service_role;
grant all on public.official_hanja_entries to service_role;
grant all on public.official_hanja_variants to service_role;
grant all on public.official_pronunciation_sources to service_role;
grant all on public.official_pronunciation_chunks to service_role;
grant all on public.official_pronunciation_entries to service_role;
grant usage, select on sequence public.official_pronunciation_chunks_id_seq to service_role;

drop policy if exists "Anyone can read production pronunciation entries" on public.official_pronunciation_entries;
create policy "Anyone can read production pronunciation entries"
  on public.official_pronunciation_entries for select
  using (
    review_status = 'production' and exists (
      select 1 from public.official_pronunciation_sources sources
      where sources.id = official_pronunciation_entries.source_id
        and sources.extraction_status = 'production'
    )
  );

drop policy if exists "Anyone can read production Hanja sources" on public.official_hanja_sources;
create policy "Anyone can read production Hanja sources"
  on public.official_hanja_sources for select
  using (status = 'production');

drop policy if exists "Anyone can read active production Hanja rules" on public.official_hanja_rules;
create policy "Anyone can read active production Hanja rules"
  on public.official_hanja_rules for select
  using (
    is_active = true and exists (
      select 1 from public.official_hanja_sources sources
      where sources.id = official_hanja_rules.source_id
        and sources.status = 'production'
    )
  );

drop policy if exists "Anyone can read production Hanja entries" on public.official_hanja_entries;
create policy "Anyone can read production Hanja entries"
  on public.official_hanja_entries for select
  using (
    review_status = 'production' and is_name_usable = true and exists (
      select 1 from public.official_hanja_sources sources
      where sources.id = official_hanja_entries.source_id
        and sources.status = 'production'
    )
  );

drop policy if exists "Anyone can read production Hanja variants" on public.official_hanja_variants;
create policy "Anyone can read production Hanja variants"
  on public.official_hanja_variants for select
  using (
    exists (
      select 1 from public.official_hanja_sources sources
      where sources.id = official_hanja_variants.source_id
        and sources.status = 'production'
    )
  );

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('official-hanja', 'official-hanja', false, 31457280, array['application/pdf'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
