create table if not exists public.site_contents (
  content_key text primary key,
  content_type text not null check (
    content_type in ('terms', 'privacy', 'refund', 'pricing', 'footer')
  ),
  locale text not null,
  draft_content jsonb not null,
  published_content jsonb,
  draft_version integer not null default 1,
  published_version integer not null default 0,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now(),
  published_at timestamptz,
  check (
    (content_type = 'footer' and locale = 'global')
    or
    (content_type <> 'footer' and locale <> 'global')
  )
);

create table if not exists public.site_content_revisions (
  id bigint generated by default as identity primary key,
  content_key text not null references public.site_contents(content_key) on delete cascade,
  action text not null check (action in ('save_draft', 'publish')),
  version integer not null,
  content jsonb not null,
  changed_by uuid references auth.users(id) on delete set null,
  changed_at timestamptz not null default now()
);

create index if not exists site_content_revisions_key_changed_idx
  on public.site_content_revisions (content_key, changed_at desc);

alter table public.site_contents enable row level security;
alter table public.site_content_revisions enable row level security;

revoke all on public.site_contents from anon, authenticated;
revoke all on public.site_content_revisions from anon, authenticated;
grant all on public.site_contents to service_role;
grant all on public.site_content_revisions to service_role;
grant usage, select on sequence public.site_content_revisions_id_seq to service_role;

-- Public reads and administrator writes go through trusted Next.js API routes.
-- Give an operator account its role from a trusted SQL session or server script:
-- update auth.users
-- set raw_app_meta_data = coalesce(raw_app_meta_data, '{}'::jsonb)
--   || '{"role":"admin"}'::jsonb
-- where email = 'operator@example.com';
