create table if not exists public.site_events (
  id bigint generated by default as identity primary key,
  event_type text not null check (
    event_type in ('PAGE_VIEW', 'ANALYSIS_STARTED', 'ANALYSIS_COMPLETED', 'ANALYSIS_FAILED')
  ),
  path text not null,
  locale text,
  country_code text check (country_code is null or country_code ~ '^[A-Z]{2}$'),
  service_type text,
  visitor_hash text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.ai_usage_logs (
  id uuid primary key default gen_random_uuid(),
  naming_log_id uuid references public.naming_logs(id) on delete set null,
  user_id uuid references auth.users(id) on delete set null,
  service_type text not null,
  model text not null,
  prompt_tokens integer not null default 0 check (prompt_tokens >= 0),
  completion_tokens integer not null default 0 check (completion_tokens >= 0),
  total_tokens integer not null default 0 check (total_tokens >= 0),
  latency_ms integer not null default 0 check (latency_ms >= 0),
  status text not null check (status in ('SUCCESS', 'ERROR')),
  provider_request_id text,
  error_code text,
  created_at timestamptz not null default now()
);

create table if not exists public.daily_usage_counters (
  usage_day date not null,
  visitor_hash text not null,
  request_count integer not null default 0 check (request_count >= 0),
  updated_at timestamptz not null default now(),
  primary key (usage_day, visitor_hash)
);

alter table public.ad_events
  add column if not exists country_code text,
  add column if not exists locale text,
  add column if not exists service_type text,
  add column if not exists visitor_hash text;

create index if not exists site_events_created_idx on public.site_events (created_at desc);
create index if not exists site_events_country_created_idx on public.site_events (country_code, created_at desc);
create index if not exists site_events_service_created_idx on public.site_events (service_type, created_at desc);
create index if not exists ai_usage_logs_created_idx on public.ai_usage_logs (created_at desc);
create index if not exists ai_usage_logs_service_created_idx on public.ai_usage_logs (service_type, created_at desc);
create index if not exists ad_events_created_idx on public.ad_events (created_at desc);
create index if not exists orders_created_idx on public.orders (created_at desc);

create or replace function public.consume_daily_quota(
  p_visitor_hash text,
  p_limit integer
) returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  next_count integer;
begin
  insert into public.daily_usage_counters (usage_day, visitor_hash, request_count)
  values (current_date, p_visitor_hash, 1)
  on conflict (usage_day, visitor_hash)
  do update set
    request_count = public.daily_usage_counters.request_count + 1,
    updated_at = now()
  returning request_count into next_count;

  if next_count > greatest(p_limit, 1) then
    update public.daily_usage_counters
      set request_count = request_count - 1, updated_at = now()
      where usage_day = current_date and visitor_hash = p_visitor_hash;
    return false;
  end if;

  return true;
end;
$$;

create or replace function public.admin_analytics_snapshot(p_days integer default 30)
returns jsonb
language sql
security definer
set search_path = public, auth
as $$
  with bounds as (
    select now() - make_interval(days => greatest(1, least(p_days, 365))) as since
  ),
  country_rows as (
    select coalesce(country_code, 'ZZ') as country_code,
           count(*) filter (where event_type = 'PAGE_VIEW')::int as visits,
           count(distinct visitor_hash)::int as visitors
    from public.site_events, bounds
    where created_at >= bounds.since
    group by coalesce(country_code, 'ZZ')
    order by visits desc
    limit 100
  ),
  service_rows as (
    select coalesce(service_type, 'UNKNOWN') as service_type,
           count(*) filter (where event_type = 'ANALYSIS_STARTED')::int as started,
           count(*) filter (where event_type = 'ANALYSIS_COMPLETED')::int as completed,
           count(*) filter (where event_type = 'ANALYSIS_FAILED')::int as failed
    from public.site_events, bounds
    where created_at >= bounds.since and service_type is not null
    group by service_type
    order by started desc
  ),
  daily_rows as (
    select to_char(date_trunc('day', created_at), 'YYYY-MM-DD') as day,
           count(*) filter (where event_type = 'PAGE_VIEW')::int as visits,
           count(*) filter (where event_type = 'ANALYSIS_COMPLETED')::int as analyses
    from public.site_events, bounds
    where created_at >= bounds.since
    group by date_trunc('day', created_at)
    order by date_trunc('day', created_at)
  ),
  order_rows as (
    select payment_status, fulfillment_status, count(*)::int as count,
           coalesce(sum(payment_amount), 0)::bigint as amount
    from public.orders, bounds
    where created_at >= bounds.since
    group by payment_status, fulfillment_status
    order by count desc
  ),
  ai_rows as (
    select model, count(*)::int as calls, coalesce(sum(total_tokens), 0)::bigint as tokens,
           coalesce(round(avg(latency_ms)), 0)::int as avg_latency_ms
    from public.ai_usage_logs, bounds
    where created_at >= bounds.since
    group by model
    order by calls desc
  )
  select jsonb_build_object(
    'days', greatest(1, least(p_days, 365)),
    'summary', jsonb_build_object(
      'members', (select count(*)::int from auth.users),
      'visits', (select count(*)::int from public.site_events, bounds where created_at >= bounds.since and event_type = 'PAGE_VIEW'),
      'visitors', (select count(distinct visitor_hash)::int from public.site_events, bounds where created_at >= bounds.since and event_type = 'PAGE_VIEW'),
      'analyses', (select count(*)::int from public.site_events, bounds where created_at >= bounds.since and event_type = 'ANALYSIS_COMPLETED'),
      'aiCalls', (select count(*)::int from public.ai_usage_logs, bounds where created_at >= bounds.since),
      'aiTokens', (select coalesce(sum(total_tokens), 0)::bigint from public.ai_usage_logs, bounds where created_at >= bounds.since),
      'adImpressions', (select count(*)::int from public.ad_events, bounds where created_at >= bounds.since and event_type = 'IMPRESSION'),
      'adRewards', (select count(*)::int from public.ad_events, bounds where created_at >= bounds.since and event_type = 'REWARD_GRANTED'),
      'orders', (select count(*)::int from public.orders, bounds where created_at >= bounds.since),
      'paidOrders', (select count(*)::int from public.orders, bounds where created_at >= bounds.since and payment_status = 'PAID'),
      'revenue', (select coalesce(sum(payment_amount), 0)::bigint from public.orders, bounds where created_at >= bounds.since and payment_status = 'PAID')
    ),
    'countries', coalesce((select jsonb_agg(to_jsonb(country_rows)) from country_rows), '[]'::jsonb),
    'services', coalesce((select jsonb_agg(to_jsonb(service_rows)) from service_rows), '[]'::jsonb),
    'daily', coalesce((select jsonb_agg(to_jsonb(daily_rows)) from daily_rows), '[]'::jsonb),
    'orderStatuses', coalesce((select jsonb_agg(to_jsonb(order_rows)) from order_rows), '[]'::jsonb),
    'aiModels', coalesce((select jsonb_agg(to_jsonb(ai_rows)) from ai_rows), '[]'::jsonb)
  );
$$;

alter table public.site_events enable row level security;
alter table public.ai_usage_logs enable row level security;
alter table public.daily_usage_counters enable row level security;

revoke all on public.site_events from anon, authenticated;
revoke all on public.ai_usage_logs from anon, authenticated;
revoke all on public.daily_usage_counters from anon, authenticated;
grant all on public.site_events to service_role;
grant all on public.ai_usage_logs to service_role;
grant all on public.daily_usage_counters to service_role;
grant usage, select on sequence public.site_events_id_seq to service_role;
revoke all on function public.consume_daily_quota(text, integer) from public, anon, authenticated;
revoke all on function public.admin_analytics_snapshot(integer) from public, anon, authenticated;
grant execute on function public.consume_daily_quota(text, integer) to service_role;
grant execute on function public.admin_analytics_snapshot(integer) to service_role;
