create table if not exists public.master_data_records (
  id uuid primary key default gen_random_uuid(),
  category text not null check (category in (
    'COUNTRY_LANGUAGE',
    'NAME_PRONUNCIATION',
    'HANJA',
    'AI_SERVICE',
    'PRODUCT_PRICING',
    'PAYMENT_SHIPPING',
    'AD_SLOT',
    'TRANSLATION_COPY',
    'SYSTEM_SETTING'
  )),
  record_key text not null,
  label text not null,
  data jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (category, record_key)
);

create table if not exists public.master_data_revisions (
  id bigint generated by default as identity primary key,
  record_id uuid not null references public.master_data_records(id) on delete cascade,
  category text not null,
  record_key text not null,
  action text not null check (action in ('CREATE', 'UPDATE', 'DEACTIVATE', 'ACTIVATE')),
  snapshot jsonb not null,
  changed_by uuid references auth.users(id) on delete set null,
  changed_at timestamptz not null default now()
);

create index if not exists master_data_category_order_idx
  on public.master_data_records (category, is_active desc, sort_order, label);
create index if not exists master_data_revisions_record_changed_idx
  on public.master_data_revisions (record_id, changed_at desc);

alter table public.master_data_records enable row level security;
alter table public.master_data_revisions enable row level security;
revoke all on public.master_data_records from anon, authenticated;
revoke all on public.master_data_revisions from anon, authenticated;
grant all on public.master_data_records to service_role;
grant all on public.master_data_revisions to service_role;
grant usage, select on sequence public.master_data_revisions_id_seq to service_role;
