// **방금 넣은 밀러 배치의 상징이 자연스러운 문장에서 실제로 걸리는지** 본다.
// (지금 담긴 것: 배치 177 — Pigeon~Pill, 8건)
//
// ## 왜 이것이 따로 있어야 하나 (2026-09-01)
//
// 배치를 넣는 절차의 ⑨단계다. ⑧까지의 검사기 셋(`verify-dream-km`·`audit-km-dead-words`·
// `verify-dream-cite`)은 **「적어 둔 것이 규칙에 맞는가」만 본다.** 「이용자가 쓸 말로
// 걸리는가」는 아무도 안 본다 — 09-01 앞 세션에서 셋 다 초록불인데 **다섯 상징이 하나도
// 안 걸렸다**(별칭을 어간으로 적어서, CLAUDE.md §25). 배치 11 에서도 이 프로브가
// **9건을 잡았다**(안 걸림 2 · 엉뚱한 뜻 7) — 검사기 셋은 그때도 전부 초록불이었다.
//
// ## 이 프로브가 못 잡는 것 (§22 — 먼저 적는다)
//
//   · 뜻이 맞는지는 안 본다. **걸리는가와 어느 의미로 갈리는가**만 본다.
//   · 한국어 문장만 본다. 영어 판별어는 여기서 안 밟힌다.
//   · 문장을 **손으로 적는다** — 새 배치를 넣으면 `CASES`를 그 배치 것으로 갈아야 한다.
//     갈지 않으면 옛 배치를 다시 재면서 「새 배치를 쟀다」고 착각한다.
//   · 지난 배치는 여기 안 남는다. 영구 회귀는 `verify-dream-match.ts`가 맡는다.
//   · **아무것도 안 걸렸을 때 떨어지는 자리(첫 의미)는 여기서 안 잰다** —
//     `probe-water-fallback.ts`와 조립기의 「기본값이 바뀐 상징」 관문이 본다.
//   · **문장을 통과하도록 고르면 안 된다.** 안 걸리면 문장이 아니라 **데이터를 고친다** —
//     이용자는 이 파일을 안 보고 자기 말로 쓴다.
//
// 재구현하지 않는다 — 제품이 쓰는 matchDream 을 그대로 부른다(CLAUDE.md §23).
//
// 실행: apps/dreamslink 에서  npx tsx scripts/probe-miller-batch.ts
// 종료 코드: 0 전부 걸림 / 1 안 걸리거나 엉뚱한 뜻으로 걸린 것이 있음
import { matchDream } from "../src/lib/engines/dream-match";

type Case = { id: string; ctx: string; text: string };

const CASES: Case[] = [
  { id: "newspaper-reporter", ctx: "신문 기자를 마지못해 봄", text: "신문 기자를 마지못해 보았다" },
  { id: "newspaper-reporter", ctx: "제가 신문 기자임을 봄", text: "내가 신문 기자였다" },
  { id: "new-year", ctx: "새해를 봄", text: "새해를 맞이했다" },
  { id: "new-year", ctx: "지친 마음으로 새해를 생각함", text: "지친 마음으로 새해를 생각했다" },
  { id: "niece", ctx: "여성이 제 조카딸을 봄", text: "여자가 제 조카딸을 보았다" },
  { id: "dark", ctx: "밤에 둘러싸임", text: "밤에 둘러싸였다" },
  { id: "dark", ctx: "밤이 걷히는 것을 봄", text: "밤이 걷히는 것을 보았다" },
  { id: "nightmare", ctx: "악몽에 사로잡힘", text: "악몽에 사로잡혔다" },
  { id: "nightmare", ctx: "처녀가 악몽에 사로잡힘", text: "처녀가 악몽에 사로잡혔다" },
  { id: "nightingale", ctx: "나이팅게일의 고운 노래를 들음", text: "나이팅게일의 고운 노래를 들었다" },
  { id: "nightingale", ctx: "나이팅게일이 잠잠한 것을 봄", text: "나이팅게일이 잠잠한 것을 보았다" },
  { id: "ninepins", ctx: "구주희를 함", text: "구주희를 했다" },
  { id: "nobility", ctx: "귀족과 어울림", text: "귀족과 어울렸다" },
  { id: "nobility", ctx: "처녀가 귀족 꿈을 꿈", text: "처녀가 귀족 꿈을 꾸었다" },
  { id: "noise", ctx: "이상한 소음을 들음", text: "이상한 소음을 들었다" },
  { id: "noise", ctx: "소음에 잠을 깸", text: "소음에 잠에서 깨어났다" },
  { id: "noodles", ctx: "국수를 봄", text: "국수를 보았다" },
  { id: "nose", ctx: "제 코를 봄", text: "제 코를 보았다" },
  { id: "nose", ctx: "제 코가 원래보다 작아 보임", text: "코가 원래보다 작아 보였다" },
  { id: "nose", ctx: "코에 털이 남을 봄", text: "코에 털이 자랐다" },
  { id: "bleeding", ctx: "코피가 남", text: "코피가 났다" },
  { id: "notary", ctx: "공증인을 봄", text: "공증인을 보았다" },
  { id: "notary", ctx: "여성이 공증인과 어울림", text: "여자가 공증인과 어울렸다" },
  { id: "november", ctx: "11월 꿈을 꿈", text: "11월 꿈을 꾸었다" },
  { id: "ache", ctx: "몸에 저림이 스멀스멀 번짐", text: "몸에 저림이 스멀스멀 번졌다" },
  { id: "figure", ctx: "숫자 때문에 사업이 어수선함", text: "숫자 때문에 사업이 어수선해졌다" },
  // 지킴 — 이번 배치가 건드린 기존 상징의 옛 답이 그대로인가(§25 곁가지 · §30 곁가지)
  { id: "dark", ctx: "길을 가다 어둠이 덮침", text: "길을 가다가 어둠이 덮쳤다" },
  { id: "dark", ctx: "어둠 속에서 벗이나 아이를 잃음", text: "어둠 속에서 아이를 잃어버렸다" },
  { id: "ache", ctx: "몸에 통증이 있음", text: "온몸에 통증이 있었다" },
  { id: "figure", ctx: "숫자를 봄", text: "숫자를 보았다" },
  { id: "bleeding", ctx: "피를 흘리는 꿈을 꿈", text: "피를 흘리는 꿈을 꾸었다" },
  { id: "nuns", ctx: "신앙심 깊은 남성이 수녀 꿈을 꿈", text: "신앙심 깊은 남성이 수녀 꿈을 꾸었다" },
  { id: "nuns", ctx: "여성이 수녀 꿈을 꿈", text: "여자가 수녀 꿈을 꾸었다" },
  { id: "nuns", ctx: "여성이 제가 수녀임을 봄", text: "제가 수녀임을 문득 깨달았다" },
  { id: "nuns", ctx: "죽은 수녀를 봄", text: "죽은 수녀를 보았다" },
  { id: "nuns", ctx: "수녀가 수도복을 벗어 버림", text: "수녀가 수도복을 벗어 버렸다" },
  { id: "wedding", ctx: "여성이 제 혼례를 봄", text: "여자가 혼인하여 이름을 얻고 화목을 누리는 꿈을 꾸었다" },
  { id: "nurse", ctx: "집에 간호사를 둠", text: "집에 간호사를 두었다" },
  { id: "nurse", ctx: "간호사가 집을 나서는 것을 봄", text: "간호사가 집을 나서는 것을 보았다" },
  { id: "nurse", ctx: "처녀가 제가 간호사임을 봄", text: "처녀가 제가 간호사임을 알았다" },
  { id: "nurse", ctx: "간호사가 환자와 헤어짐", text: "간호사가 환자와 헤어졌다" },
  { id: "nursing", ctx: "여성이 제 아기에게 젖을 물림", text: "여자가 제 아기에게 젖을 물렸다" },
  { id: "nursing", ctx: "처녀가 아기에게 젖을 물림", text: "처녀가 아기에게 젖을 물렸다" },
  { id: "nursing", ctx: "남성이 아내가 아기에게 젖을 물리는 것을 봄", text: "남자가 아내가 아기에게 젖을 물리는 것을 보았다" },
  { id: "nuts", ctx: "견과를 주움", text: "견과를 주웠다" },
  { id: "nuts", ctx: "견과를 먹음", text: "견과를 먹었다" },
  { id: "nuts", ctx: "여성이 견과 꿈을 꿈", text: "여자가 견과 꿈을 꾸었다" },
  { id: "nutmegs", ctx: "육두구 꿈을 꿈", text: "육두구 꿈을 꾸었다" },
  { id: "nymph", ctx: "님프가 맑은 물에서 목욕하는 것을 봄", text: "님프가 맑은 물에서 목욕하는 것을 보았다" },
  { id: "nymph", ctx: "님프가 제 영역을 벗어나 있는 것을 봄", text: "님프가 제 영역을 벗어나 있었다" },
  { id: "nymph", ctx: "처녀가 님프가 목욕하는 것을 봄", text: "처녀가 님프가 목욕하는 것을 보았다" },
  { id: "nymph", ctx: "처녀가 제가 님프인 척함", text: "처녀가 제가 님프인 척했다" },
  { id: "oak", ctx: "참나무 숲을 봄", text: "참나무 숲을 보았다" },
  { id: "oak", ctx: "도토리가 가득한 참나무를 봄", text: "도토리가 가득한 참나무를 보았다" },
  { id: "oak", ctx: "벼락 맞은 참나무를 봄", text: "벼락 맞은 참나무를 보았다" },
  { id: "oak", ctx: "연인들이 참나무 꿈을 꿈", text: "연인들이 참나무 꿈을 꾸었다" },
  { id: "oar", ctx: "노를 저음", text: "노를 저었다" },
  { id: "oar", ctx: "노를 잃어버림", text: "노를 잃어버렸다" },
  { id: "oar", ctx: "노가 부러짐", text: "노가 부러졌다" },
  { id: "oath", ctx: "맹세를 함", text: "맹세를 했다" },
  { id: "oatmeal", ctx: "오트밀을 먹음", text: "오트밀을 먹었다" },
  { id: "oatmeal", ctx: "처녀가 오트밀을 상에 차림", text: "처녀가 오트밀을 상에 차렸다" },
  { id: "oats", ctx: "귀리가 눈에 가득함", text: "귀리가 눈에 가득했다" },
  { id: "oats", ctx: "썩은 귀리를 봄", text: "썩은 귀리를 보았다" },
  { id: "obedience", ctx: "남에게 순종함", text: "남에게 순종했다" },
  { id: "obedience", ctx: "남들이 나에게 순종함", text: "남들이 나에게 순종했다" },
  { id: "obelisk", ctx: "오벨리스크가 위엄 있고 차갑게 솟아 있음을 봄", text: "오벨리스크가 위엄 있고 차갑게 솟아 있었다" },
  { id: "obelisk", ctx: "연인들이 오벨리스크 밑에 섬", text: "연인들이 오벨리스크 밑에 섰다" },
  { id: "obituary", ctx: "부고를 씀", text: "부고를 썼다" },
  { id: "obituary", ctx: "부고를 읽음", text: "부고를 읽었다" },
  { id: "obligation", ctx: "스스로 책무를 짐", text: "스스로 책무를 졌다" },
  { id: "obligation", ctx: "남들이 나에게 책무를 짐", text: "남들이 나에게 책무를 졌다" },
  { id: "observatory", ctx: "천문대에서 하늘을 봄", text: "천문대에서 하늘을 보았다" },
  { id: "observatory", ctx: "처녀가 천문대에서 하늘을 봄", text: "처녀가 천문대에서 하늘을 보았다" },
  { id: "observatory", ctx: "천문대에서 본 하늘이 흐림", text: "천문대에서 본 하늘이 흐렸다" },
  { id: "occultist", ctx: "신비주의자의 가르침을 들음", text: "신비주의자의 가르침을 들었다" },
  { id: "occultist", ctx: "신비주의자의 견해를 받아들임", text: "신비주의자의 견해를 받아들였다" },
  { id: "sea", ctx: "바다가 잔잔함", text: "바다가 잔잔했다" },
  { id: "sea", ctx: "먼바다에서 파도가 배를 침", text: "먼바다에서 파도가 배를 쳤다" },
  { id: "sea", ctx: "물가에서 파도가 부서지는 것을 봄", text: "물가에서 파도가 부서지는 것을 보았다" },
  { id: "sea", ctx: "바다가 얕아 걸어 들어갈 만함을 봄", text: "바다가 얕아 걸어 들어갈 만했다" },
  // 지킴 — 이번 배치가 건드린 기존 상징의 옛 답이 그대로인가
  { id: "sea", ctx: "강과 바다가 넘쳐 불어남", text: "강과 바다가 넘쳐 불어났다" },
  { id: "october", ctx: "10월이라고 상상함", text: "10월이라고 상상했다" },
  { id: "oculist", ctx: "안과의사와 상담함", text: "안과의사와 상담했다" },
  { id: "odd-fellow", ctx: "우애조합을 봄", text: "우애조합을 보았다" },
  { id: "odd-fellow", ctx: "우애조합에 가입함", text: "우애조합에 가입했다" },
  { id: "odor", ctx: "달콤한 냄새를 맡음", text: "달콤한 냄새를 맡았다" },
  { id: "odor", ctx: "역겨운 냄새를 맡음", text: "역겨운 냄새를 맡았다" },
  { id: "humiliation", ctx: "모욕당했다고 느낌", text: "제 행실의 잘못이 드러나 속으로 분노하며 모욕당했다" },
  { id: "humiliation", ctx: "남에게 모욕을 줌", text: "남에게 모욕을 주었다" },
  { id: "humiliation", ctx: "처녀가 모욕을 주거나 받음", text: "처녀가 모욕을 주거나 받았다" },
  { id: "offering", ctx: "제물을 바침", text: "제물을 바쳤다" },
  { id: "official-post", ctx: "관직을 지님", text: "관직을 지녔다" },
  { id: "official-post", ctx: "바라던 관직을 얻지 못함", text: "바라던 관직을 얻지 못했다" },
  { id: "official-post", ctx: "관직에서 쫓겨남", text: "관직에서 쫓겨났다" },
  { id: "child", ctx: "제 자식을 봄", text: "제 자식을 보았다" },
  { id: "brood", ctx: "집짐승의 새끼를 봄", text: "집짐승의 새끼를 보았다" },
  { id: "oil", ctx: "기름을 바르는 의식을 치름", text: "기름을 바르는 의식을 치렀다" },
  { id: "oil", ctx: "기름이 많이 있는 것을 봄", text: "기름이 많이 있는 것을 보았다" },
  { id: "oil", ctx: "남성이 기름 장사를 함", text: "남자가 기름 장사를 했다" },
  { id: "oil", ctx: "여성이 기름을 바름", text: "여자가 기름을 발랐다" },
  { id: "oilcloth", ctx: "방수포를 봄", text: "방수포를 보았다" },
  { id: "oilcloth", ctx: "방수포 장사를 함", text: "방수포 장사를 했다" },
  // 지킴 — 이번 배치가 건드린 기존 상징의 옛 답이 그대로인가
  { id: "humiliation", ctx: "모욕당하는 꿈을 꿈", text: "모욕당하는 꿈을 꾸었다" },
  { id: "official-post", ctx: "새로 벼슬을 받음", text: "새로 벼슬을 받았다" },
  { id: "child", ctx: "아름다운 아이들을 여럿 봄", text: "아름다운 아이들을 여럿 보았다" },
  { id: "ointment", ctx: "연고 꿈을 꿈", text: "연고 꿈을 꾸었다" },
  { id: "ointment", ctx: "처녀가 연고를 만듦", text: "처녀가 연고를 만들었다" },
  { id: "old-man-or-woman", ctx: "노인을 봄", text: "노인을 보았다" },
  { id: "olives", ctx: "즐거운 벗들과 올리브를 땀", text: "즐거운 벗들과 올리브를 땄다" },
  { id: "olives", ctx: "병에서 올리브를 꺼냄", text: "병에서 올리브를 꺼냈다" },
  { id: "olives", ctx: "올리브 병을 깨뜨림", text: "올리브 병을 깨뜨렸다" },
  { id: "olives", ctx: "올리브를 먹음", text: "올리브를 먹었다" },
  { id: "omelet", ctx: "오믈렛이 나오는 것을 봄", text: "오믈렛이 나오는 것을 보았다" },
  { id: "omelet", ctx: "오믈렛을 먹음", text: "오믈렛을 먹었다" },
  { id: "carriage", ctx: "합승마차를 타고 거리를 지남", text: "합승마차를 타고 거리를 지났다" },
  { id: "one-eyed", ctx: "애꾸눈 생물을 봄", text: "애꾸눈 생물을 보았다" },
  { id: "onions", ctx: "양파가 많이 있는 것을 봄", text: "양파가 많이 있는 것을 보았다" },
  { id: "onions", ctx: "양파를 먹음", text: "양파를 먹었다" },
  { id: "onions", ctx: "양파가 자라는 것을 봄", text: "양파가 자라는 것을 보았다" },
  { id: "onions", ctx: "익힌 양파를 봄", text: "익힌 양파를 보았다" },
  { id: "onions", ctx: "양파를 썰다가 눈에 즙이 스밈", text: "양파를 썰다가 눈에 즙이 스몄다" },
  { id: "opera", ctx: "오페라를 관람함", text: "오페라를 관람했다" },
  { id: "laudanum", ctx: "아편 꿈을 꿈", text: "아편 꿈을 꾸었다" },
  // 지킴 — 이번 배치가 건드린 기존 상징의 옛 답이 그대로인가
  { id: "carriage", ctx: "마차를 타고 감", text: "마차를 타고 갔다" },
  { id: "laudanum", ctx: "아편을 먹음", text: "아편을 먹었다" },
  { id: "luxury", ctx: "처녀가 요정 같은 호사 속에 삶을 봄", text: "처녀가 요정 같은 호사 속에 사는 꿈을 꾸었다" },
  { id: "wealth", ctx: "처녀가 참된 재물과 안락을 누림", text: "처녀가 참된 재물과 안락을 누렸다" },
  { id: "oranges", ctx: "건강한 오렌지 나무들을 봄", text: "건강한 오렌지 나무들을 보았다" },
  { id: "oranges", ctx: "오렌지를 먹음", text: "오렌지를 먹었다" },
  { id: "oranges", ctx: "처녀가 오렌지를 먹는 꿈을 꿈", text: "처녀가 오렌지를 먹는 꿈을 꾸어 정인을 잃었다" },
  { id: "oranges", ctx: "처녀가 높이 던져 올린 좋은 오렌지를 봄", text: "처녀가 높이 던져 올린 좋은 오렌지를 보았다" },
  { id: "oranges", ctx: "오렌지 껍질에 미끄러짐", text: "오렌지 껍질에 미끄러졌다" },
  { id: "oranges", ctx: "아내의 청으로 오렌지를 사고 아내가 먹음", text: "아내의 청으로 오렌지를 사고 아내가 먹었다" },
  { id: "orang-utang", ctx: "오랑우탄 꿈을 꿈", text: "오랑우탄 꿈을 꾸었다" },
  { id: "orang-utang", ctx: "처녀가 오랑우탄 꿈을 꿈", text: "처녀가 오랑우탄 꿈을 꾸었다" },
  { id: "orator", ctx: "웅변가의 언변에 홀림", text: "웅변가의 언변에 홀렸다" },
  { id: "orator", ctx: "처녀가 웅변가와 사랑에 빠짐", text: "처녀가 웅변가와 사랑에 빠졌다" },
  { id: "orchard", ctx: "정인과 함께 꽃 핀 과수원을 지남", text: "정인과 함께 꽃이 만발한 과수원을 지났다" },
  { id: "orchard", ctx: "과수원에 무르익은 열매가 가득함", text: "과수원에 무르익은 열매가 가득했다" },
  { id: "orchard", ctx: "과수원에서 돼지가 떨어진 열매를 먹는 것을 봄", text: "과수원에서 돼지가 떨어진 열매를 먹는 것을 보았다" },
  { id: "orchard", ctx: "잘 익은 열매를 거둠", text: "과수원에서 잘 익은 열매를 거두었다" },
  { id: "orchard", ctx: "과수원에 병충해가 듦", text: "과수원에 병충해가 들었다" },
  { id: "orchard", ctx: "과수원을 지나다 가시덤불에 걸림", text: "과수원을 지나다 가시덤불에 걸렸다" },
  { id: "orchard", ctx: "황폐한 과수원을 봄", text: "황폐한 과수원을 보았다" },
  { id: "orchard", ctx: "겨울에 잎이 진 과수원을 봄", text: "겨울처럼 잎이 진 과수원을 보았다" },
  { id: "orchard", ctx: "폭풍이 휩쓴 과수원을 봄", text: "폭풍이 휩쓴 과수원을 보았다" },
  // 지킴 — 이번 배치가 건드린 기존 상징의 옛 답이 그대로인가
  { id: "luxury", ctx: "사치에 둘러싸임", text: "사치에 둘러싸였다" },
  { id: "wealth", ctx: "집안에서 재물을 나눔", text: "집안에서 재물을 나누었다" },
  { id: "orchard", ctx: "과수원 속을 거닒", text: "과수원 속을 거닐었다" },
  { id: "orchestra", ctx: "오케스트라에 속해 연주함", text: "오케스트라에 속해 연주했다" },
  { id: "orchestra", ctx: "오케스트라의 음악을 들음", text: "오케스트라의 음악을 들었다" },
  { id: "organ", ctx: "오르간이 장엄한 찬가를 울림", text: "오르간이 장엄한 찬가를 울렸다" },
  { id: "organ", ctx: "교회에서 오르간을 봄", text: "교회에서 오르간을 보았다" },
  { id: "organ", ctx: "오르간으로 조화로운 음악을 연주함", text: "오르간으로 조화로운 음악을 연주했다" },
  { id: "organ", ctx: "구슬픈 노래와 오르간 반주를 들음", text: "구슬픈 노래와 오르간 반주를 들었다" },
  { id: "organist", ctx: "오르간 연주자를 봄", text: "오르간 연주자를 보았다" },
  { id: "organist", ctx: "처녀가 제가 오르간 연주자임을 봄", text: "처녀가 제가 오르간 연주자임을 알았다" },
  { id: "ornament", ctx: "장식품을 착용함", text: "장식품을 착용했다" },
  { id: "ornament", ctx: "장식품을 받음", text: "장식품을 받았다" },
  { id: "ornament", ctx: "장식품을 남에게 줌", text: "장식품을 남에게 주었다" },
  { id: "ornament", ctx: "장식품을 잃어버림", text: "장식품을 잃어버렸다" },
  { id: "orphan", ctx: "고아를 위로함", text: "고아를 위로했다" },
  { id: "orphan", ctx: "친척인 고아가 있음", text: "친척인 고아가 있었다" },
  { id: "ostrich", ctx: "타조 꿈을 꿈", text: "타조 꿈을 꾸었다" },
  { id: "ostrich", ctx: "타조를 붙잡음", text: "타조를 붙잡았다" },
  { id: "otter", ctx: "수달이 맑은 물살에서 노니는 것을 봄", text: "수달이 맑은 물살에서 노니는 것을 보았다" },
  { id: "couch", ctx: "소파에 기대어 정인과 사랑을 속삭임", text: "소파에 기대어 정인과 사랑을 속삭였다" },
  // 지킴 — 이번 배치가 건드린 기존 상징의 옛 답이 그대로인가
  { id: "couch", ctx: "긴 소파에 기대어 누움", text: "긴 소파에 기대어 누웠다" },
  { id: "ouija", ctx: "위자보드로 점을 침", text: "위자보드로 점을 쳤다" },
  { id: "ouija", ctx: "위자보드가 작동하지 않음", text: "위자보드가 작동하지 않았다" },
  { id: "ouija", ctx: "위자보드가 술술 글자를 씀", text: "위자보드가 술술 글자를 썼다" },
  { id: "ouija", ctx: "잃어버린 위자보드를 되찾음", text: "잃어버린 위자보드를 되찾았다" },
  { id: "oven", ctx: "여성의 오븐이 새빨갛게 달아오름", text: "여성의 오븐이 새빨갛게 달아올랐다" },
  { id: "oven", ctx: "오븐이 고장 남", text: "오븐이 고장 났다" },
  { id: "coat", ctx: "외투 꿈을 꿈", text: "외투 꿈을 꾸었다" },
  { id: "coat", ctx: "외투를 빌림", text: "낯선 이들의 실수로 외투를 빌렸다가 불운을 겪었다" },
  { id: "over-alls", ctx: "여성이 남자가 작업복 입은 것을 봄", text: "여성이 남자가 작업복 입은 것을 보았다" },
  { id: "over-alls", ctx: "아내가 남편의 잦은 부재를 의심함", text: "아내가 남편이 작업복 입은 것을 보고 그의 잦은 부재를 의심했다" },
  { id: "owl", ctx: "부엉이의 엄숙하고 기이한 소리를 들음", text: "부엉이의 엄숙하고 기이한 소리를 들었다" },
  { id: "owl", ctx: "죽은 부엉이를 봄", text: "죽은 부엉이를 보았다" },
  { id: "owl", ctx: "부엉이를 봄", text: "부엉이를 보니 은밀히 헐뜯음을 당하고 원수의 위험에 놓일까 두려웠다" },
  // 지킴 — 이번 배치가 건드린 기존 상징의 옛 답이 그대로인가
  { id: "coat", ctx: "남의 외투를 입음", text: "남의 외투를 입었다" },
  { id: "coat", ctx: "외투가 찢어진 것을 봄", text: "외투가 찢어진 것을 보았다" },
  { id: "coat", ctx: "새 외투를 봄", text: "새로운 외투를 보았다" },
  { id: "coat", ctx: "외투를 잃어버림", text: "외투를 잃어버렸다" },
  { id: "baking", ctx: "여성이 빵 굽는 꿈을 꿈", text: "여성이 빵 굽는 꿈을 꾸었다" },
  { id: "ox", ctx: "잘 먹여 살진 소를 봄", text: "잘 먹여 살진 소를 보았다" },
  { id: "ox", ctx: "짝 맞춰 멍에를 씌운 소를 봄", text: "짝 맞춰 멍에를 씌운 소를 보았다" },
  { id: "ox", ctx: "죽은 소를 봄", text: "죽은 소를 보았다" },
  { id: "ox", ctx: "소가 맑은 못이나 시내에서 물을 마심", text: "소가 맑은 못에서 물을 마셨다" },
  { id: "oysters", ctx: "굴을 먹음", text: "굴을 먹었다" },
  { id: "oysters", ctx: "굴 장사를 함", text: "굴 장사를 했다" },
  { id: "oysters", ctx: "굴을 봄", text: "굴을 보았다" },
  { id: "oyster-shells", ctx: "굴 껍데기를 봄", text: "굴 껍데기를 보았다" },
  { id: "pacify", ctx: "괴로운 이들을 달램", text: "괴로운 이들을 달랬다" },
  { id: "pacify", ctx: "남의 분노를 달램", text: "남의 분노를 달랬다" },
  { id: "pacify", ctx: "정인이 애인의 질투 어린 의심을 달램", text: "정인이 애인의 질투 어린 의심을 달랬다" },
  { id: "packet", ctx: "소포가 들어오는 것을 봄", text: "소포가 들어오는 것을 보았다" },
  { id: "packet", ctx: "소포가 나가는 것을 봄", text: "소포가 나가는 것을 보았다" },
  // 지킴 — 이번 배치가 건드린 기존 상징의 옛 답이 그대로인가
  { id: "ox", ctx: "누런 소가 집으로 옴", text: "누런 소가 집으로 왔다" },
  { id: "cattle", ctx: "살진 소떼가 푸른 목장에서 한가로이 풀을 뜯음", text: "살진 소떼가 푸른 목장에서 한가로이 풀을 뜯었다" },
  { id: "bucket", ctx: "젖이 가득한 통을 봄", text: "젖이 가득 담긴 통을 보았다" },
  { id: "bucket", ctx: "처녀가 통을 나름", text: "처녀가 통을 날랐다" },
  { id: "agony", ctx: "제가 아파함", text: "하찮은 일로 부질없는 후회만 남기며 아파했다" },
  { id: "agony", ctx: "남이 아파하는 것을 봄", text: "남이 아파하는 것을 보았다" },
  { id: "painting", ctx: "새로 페인트칠한 집을 봄", text: "새로 페인트칠한 집을 보았다" },
  { id: "painting", ctx: "옷에 페인트가 묻음", text: "옷에 페인트가 묻었다" },
  { id: "painting", ctx: "스스로 붓을 쥐고 칠함", text: "스스로 붓을 쥐고 칠했다" },
  { id: "painting", ctx: "아름다운 그림들을 봄", text: "아름다운 그림들을 보았다" },
  { id: "painting", ctx: "처녀가 그림을 그림", text: "처녀가 그림을 그렸다" },
  { id: "palace", ctx: "궁궐을 거닐며 웅장함에 감탄함", text: "궁궐을 거닐며 웅장함에 감탄했다" },
  { id: "palace", ctx: "신사 숙녀들이 춤추고 담소하는 것을 보고 들음", text: "궁궐에서 신사 숙녀들이 춤추고 담소하는 것을 보고 들었다" },
  { id: "palace", ctx: "형편이 넉넉지 않은 처녀가 잔치에 대등하게 낌", text: "궁궐 꿈에서 형편이 넉넉지 않은 처녀가 잔치에 대등하게 꼈다" },
  { id: "palace", ctx: "형편이 어려운 처녀에게 이 꿈이 속임수처럼 다가옴", text: "궁궐 꿈이 형편이 어려운 처녀에게 속임수처럼 다가왔다" },
  { id: "palisade", ctx: "말뚝 울타리 꿈을 꿈", text: "말뚝 울타리 꿈을 꾸었다" },
  // 지킴 — 이번 배치가 건드린 기존 상징의 옛 답이 그대로인가
  { id: "bucket", ctx: "물통에 물이 가득 담김", text: "물통에 물이 가득 담겼다" },
  { id: "agony", ctx: "고통스러운 꿈을 꿈", text: "고통을 겪는 꿈을 꾸었다" },
  { id: "palace", ctx: "제왕의 궁궐에 들어감", text: "제왕의 궁궐에 들어갔다" },
  { id: "pall", ctx: "관보를 봄", text: "관보를 보았다" },
  { id: "pall", ctx: "관보를 들춰 시신을 봄", text: "관보를 들춰 시신을 보았다" },
  { id: "pallbearer", ctx: "상여꾼 꿈을 꿈", text: "상여꾼 꿈을 꾸었다" },
  { id: "pallbearer", ctx: "상여꾼을 봄", text: "상여꾼을 보았다" },
  { id: "pallet", ctx: "낡은 침상 꿈을 꿈", text: "낡은 침상 꿈을 꾸었다" },
  { id: "pallet", ctx: "처녀가 낡은 침상 꿈을 꿈", text: "처녀가 낡은 침상 꿈을 꾸었다" },
  { id: "palmistry", ctx: "처녀가 손금 보기 꿈을 꿈", text: "처녀가 손금 보기 꿈을 꾸었다" },
  { id: "palmistry", ctx: "나의 손금을 봄", text: "나의 손금을 보았다" },
  { id: "palmistry", ctx: "남의 손금을 봄", text: "남의 손금을 보았다" },
  { id: "palmistry", ctx: "목사의 손금을 봄", text: "목사의 손금을 보았다" },
  { id: "palm-tree", ctx: "야자수를 봄", text: "야자수를 보았다" },
  { id: "palm-tree", ctx: "처녀가 야자수 늘어선 길을 지남", text: "처녀가 야자수 늘어선 길을 지났다" },
  { id: "palm-tree", ctx: "야자수가 시듦", text: "야자수가 시들었다" },
  // 지킴 — 이번 배치가 건드린 기존 상징의 옛 답이 그대로인가
  { id: "glass", ctx: "유리 너머로 내다봄", text: "유리 너머로 내다보았다" },
  { id: "glass", ctx: "유리 그릇이나 창을 깨뜨림", text: "유리 그릇을 깨뜨렸다" },
  { id: "palsy", ctx: "제가 중풍에 걸림", text: "내가 중풍에 걸렸다" },
  { id: "palsy", ctx: "벗이 중풍에 걸림을 봄", text: "벗이 중풍에 걸린 것을 보았다" },
  { id: "palsy", ctx: "연인의 애인이 중풍에 걸림", text: "연인의 애인이 중풍에 걸렸다" },
  { id: "pancake", ctx: "팬케이크를 먹음", text: "팬케이크를 먹었다" },
  { id: "pancake", ctx: "팬케이크를 구움", text: "팬케이크를 구웠다" },
  { id: "glass", ctx: "유리판을 다룸", text: "유리판을 다뤘다" },
  { id: "glass", ctx: "유리창 너머로 남과 이야기함", text: "유리창 너머로 남과 이야기했다" },
  { id: "panorama", ctx: "파노라마를 봄", text: "파노라마를 보았다" },
  // 지킴 — 이번 배치가 건드린 기존 상징의 옛 답이 그대로인가
  { id: "leopard", ctx: "표범을 봄", text: "표범을 보았다" },
  { id: "paper", ctx: "오색 종이를 봄", text: "오색 종이를 보았다" },
  { id: "panther", ctx: "흑표범을 보고 겁에 질림", text: "흑표범을 보고 겁에 질렸다" },
  { id: "panther", ctx: "흑표범을 죽이거나 제압함", text: "흑표범을 죽이거나 제압했다" },
  { id: "panther", ctx: "흑표범이 위협하듯 나타남", text: "흑표범이 위협하듯 나타났다" },
  { id: "panther", ctx: "흑표범 울음소리를 듣고 공포를 느낌", text: "흑표범 울음소리를 듣고 공포를 느꼈다" },
  { id: "pantomime", ctx: "무언극을 봄", text: "무언극을 보았다" },
  { id: "pantomime", ctx: "무언극에 참여함", text: "무언극에 참여했다" },
  { id: "paper", ctx: "종이나 양피지를 다루거나 참조함", text: "종이나 양피지를 다루거나 참조했다" },
  { id: "paper", ctx: "처녀가 종이나 양피지 꿈을 꿈", text: "처녀가 종이나 양피지 꿈을 꾸었다" },
  { id: "paper", ctx: "기혼자가 종이나 양피지 꿈을 꿈", text: "기혼자가 종이나 양피지 꿈을 꾸었다" },
  // 지킴 — 이번 배치가 건드린 기존 상징의 옛 답이 그대로인가
  { id: "heaven", ctx: "하늘나라로 올라감", text: "하늘나라로 올라갔다" },
  { id: "packet", ctx: "소포가 들어오는 것을 봄", text: "소포가 들어오는 것을 보았다" },
  { id: "packet", ctx: "소포가 나가는 것을 봄", text: "소포가 나가는 것을 보았다" },
  { id: "umbrella", ctx: "남과 우산을 나눔", text: "남과 우산을 나눴다" },
  { id: "parable", ctx: "비유 꿈을 꿈", text: "비유 꿈을 꾸었다" },
  { id: "parable", ctx: "연인이나 처녀가 비유 꿈을 꿈", text: "연인이 비유 꿈을 꾸었다" },
  { id: "paradise", ctx: "낙원에 있음", text: "낙원에 있었다" },
  { id: "paradise", ctx: "선원이나 장도에 오른 이가 낙원 꿈을 꿈", text: "선원이 낙원 꿈을 꾸었다" },
  { id: "paradise", ctx: "어머니가 낙원 꿈을 꿈", text: "어머니가 낙원 꿈을 꾸었다" },
  { id: "paradise", ctx: "병약자가 낙원 꿈을 꿈", text: "병약자가 낙원 꿈을 꾸었다" },
  { id: "paradise", ctx: "연인이 낙원 꿈을 꿈", text: "연인이 낙원 꿈을 꾸었다" },
  { id: "paradise", ctx: "낙원으로 가다 헤매고 길을 잃음", text: "낙원으로 가다 헤매고 길을 잃었다" },
  { id: "paralysis", ctx: "마비에 걸림", text: "마비에 걸렸다" },
  { id: "paralysis", ctx: "연인이 마비에 걸림", text: "연인이 마비에 걸렸다" },
  { id: "umbrella", ctx: "기혼자가 양산 꿈을 꿈", text: "기혼자가 양산 꿈을 꾸었다" },
  { id: "umbrella", ctx: "처녀가 양산 꿈을 꿈", text: "처녀가 양산 꿈을 꾸었다" },
  { id: "packet", ctx: "제게 소포가 배달됨", text: "제게 소포가 배달되었다" },
  { id: "packet", ctx: "소포를 나름", text: "소포를 날랐다" },
  { id: "packet", ctx: "소포를 배달하다 길에서 떨어뜨림", text: "소포를 배달하다 길에서 떨어뜨렸다" },
  // 지킴 — 이번 배치가 건드린 기존 상징의 옛 답이 그대로인가
  { id: "pardon", ctx: "큰 사면을 받음", text: "큰 사면을 받았다" },
  { id: "father", ctx: "아버지를 봄", text: "아버지를 보았다" },
  { id: "mother", ctx: "집에 있는 어머니를 봄", text: "집에 있는 어머니를 보았다" },
  { id: "pardon", ctx: "저지르지 않은 잘못을 용서받으려 함", text: "저지르지 않은 잘못을 용서받으려 했다" },
  { id: "pardon", ctx: "실제로 잘못을 저지른 채 용서를 구함", text: "실제로 잘못을 저지른 채 용서를 구했다" },
  { id: "parents", ctx: "부모가 즐거워 보임", text: "부모가 즐거워 보였다" },
  { id: "parents", ctx: "돌아가신 부모가 나타남", text: "돌아가신 부모가 나타났다" },
  { id: "parents", ctx: "살아있는 부모가 집에서 행복해 보임", text: "살아있는 부모가 집에서 행복해 보였다" },
  { id: "parents", ctx: "처녀가 부모가 집에서 행복한 꿈을 꿈", text: "처녀가 부모가 집에서 행복한 꿈을 꾸었다" },
  { id: "parents", ctx: "부모가 창백하고 검은 옷을 입고 나타남", text: "부모가 창백하고 검은 옷을 입고 나타났다" },
  { id: "parents", ctx: "부모가 건강하고 만족스러워 보임", text: "부모가 건강하고 만족스러워 보였다" },
  { id: "parents", ctx: "부모가 편찮거나 슬퍼 보임", text: "부모가 편찮거나 슬퍼 보였다" },
  // 지킴 — 이번 배치가 건드린 기존 상징의 옛 답이 그대로인가
  { id: "parrot", ctx: "앵무새를 봄", text: "앵무새를 보았다" },
  { id: "park", ctx: "잘 가꾼 공원을 거님", text: "잘 가꾼 공원을 거닐었다" },
  { id: "park", ctx: "연인과 공원을 거님", text: "연인과 공원을 거닐었다" },
  { id: "park", ctx: "풀과 나무가 시든 공원을 봄", text: "풀과 나무가 시든 공원을 보았다" },
  { id: "parrot", ctx: "앵무새들이 재잘거림", text: "앵무새들이 재잘거렸다" },
  { id: "parrot", ctx: "가만히 있는 앵무새를 봄", text: "가만히 있는 앵무새를 보았다" },
  { id: "parrot", ctx: "처녀가 앵무새를 가짐", text: "처녀가 앵무새를 가졌다" },
  { id: "parrot", ctx: "앵무새를 가르침", text: "앵무새를 가르쳤다" },
  { id: "parrot", ctx: "죽은 앵무새를 봄", text: "죽은 앵무새를 보았다" },
  { id: "parsley", ctx: "파슬리를 봄", text: "파슬리를 보았다" },
  { id: "parsley", ctx: "파슬리를 먹음", text: "파슬리를 먹었다" },
  { id: "parsnip", ctx: "파스닙을 보거나 먹음", text: "파스닙을 보았다" },
  { id: "parting", ctx: "벗과 작별함", text: "벗과 작별했다" },
  { id: "parting", ctx: "원수와 헤어짐", text: "원수와 헤어졌다" },
  { id: "partner", ctx: "동업자가 사기그릇 바구니를 지다 떨어뜨려 뒤섞음", text: "동업자가 사기그릇 바구니를 지다 떨어뜨려 뒤섞었다" },
  { id: "partner", ctx: "그 일로 동업자를 꾸짖음", text: "그 일로 동업자를 꾸짖었다" },
  { id: "partnership", ctx: "남자와 동업을 맺음", text: "남자와 동업을 맺었다" },
  { id: "partnership", ctx: "여자와 동업함", text: "여자와 동업했다" },
  { id: "partnership", ctx: "불쾌했던 동업을 해소함", text: "불쾌했던 동업을 해소했다" },
  { id: "partnership", ctx: "즐거웠던 동업을 해소함", text: "즐거웠던 동업을 해소했다" },
  { id: "partridge", ctx: "자고새를 봄", text: "자고새를 보았다" },
  { id: "partridge", ctx: "자고새를 덫으로 잡음", text: "자고새를 덫으로 잡았다" },
  { id: "partridge", ctx: "자고새를 죽임", text: "자고새를 죽였다" },
  { id: "partridge", ctx: "자고새를 먹음", text: "자고새를 먹었다" },
  { id: "partridge", ctx: "자고새가 나는 것을 봄", text: "자고새가 나는 것을 보았다" },
  // 지킴 — 이번 배치가 건드린 기존 상징의 옛 답이 그대로인가
  { id: "bell", ctx: "종이 조종처럼 울리는 소리를 들음", text: "종이 조종처럼 울리는 소리를 들었다" },
  { id: "entertainment", ctx: "풍악과 춤이 있는 연회에 감", text: "풍악과 춤이 있는 연회에 갔다" },
  { id: "cipher", ctx: "암호를 읽음", text: "암호를 읽었다" },
  { id: "gang", ctx: "정체 모를 무리가 돈이나 재물을 노리고 덮침", text: "정체 모를 무리가 돈이나 재물을 노리고 덮쳤다" },
  { id: "gang", ctx: "다치지 않고 벗어남", text: "무리에게서 다치지 않고 벗어났다" },
  { id: "entertainment", ctx: "즐거움을 위해 파티에 참석함", text: "즐거움을 위해 파티에 참석했다" },
  { id: "passenger", ctx: "짐을 갖고 들어오는 승객들을 봄", text: "짐을 갖고 들어오는 승객들을 보았다" },
  { id: "passenger", ctx: "승객들이 떠남", text: "승객들이 떠났다" },
  { id: "passenger", ctx: "제가 집을 떠나는 승객 중 하나임", text: "제가 집을 떠나는 승객 중 하나였다" },
  { id: "bell", ctx: "직접 조종을 울림", text: "직접 조종을 울렸다" },
  { id: "password", ctx: "암호 꿈을 꿈", text: "암호 꿈을 꾸었다" },
  { id: "password", ctx: "여성이 암호를 넘겨줌", text: "여성이 암호를 넘겨주었다" },
  { id: "pasteboard", ctx: "판지 꿈을 꿈", text: "판지 꿈을 꾸었다" },
  { id: "pasteboard", ctx: "판지를 자름", text: "판지를 잘랐다" },
  { id: "pastry", ctx: "패스트리 꿈을 꿈", text: "패스트리 꿈을 꾸었다" },
  { id: "pastry", ctx: "패스트리를 먹음", text: "패스트리를 먹었다" },
  { id: "pastry", ctx: "처녀가 패스트리를 만드는 꿈을 꿈", text: "처녀가 패스트리를 만드는 꿈을 꾸었다" },
  // 지킴 — 이번 배치가 건드린 기존 상징의 옛 답이 그대로인가
  { id: "cloth", ctx: "손에 천을 감아 묶음", text: "손에 천을 감아 묶었다" },
  { id: "patch", ctx: "옷에 기운 자국을 댐", text: "옷에 기운 자국을 댔다" },
  { id: "patch", ctx: "남이 기운 자국을 댄 옷을 입은 것을 봄", text: "남이 기운 자국을 댄 옷을 입은 것을 보았다" },
  { id: "patch", ctx: "처녀가 새 옷에서 기운 자국을 발견함", text: "처녀가 새 옷에서 기운 자국을 발견했다" },
  { id: "patch", ctx: "처녀가 기운 자국을 숨기려 함", text: "처녀가 기운 자국을 숨기려 했다" },
  { id: "patch", ctx: "처녀가 옷을 깁고 있음", text: "처녀가 옷을 깁고 있었다" },
  { id: "patch", ctx: "여인이 집안일로 옷을 기움", text: "여인이 집안일로 옷을 기웠다" },
  // 지킴 — 이번 배치가 건드린 기존 상징의 옛 답이 그대로인가
  { id: "road", ctx: "사방으로 길이 뚫려 있음", text: "사방으로 길이 뚫려 있었다" },
  { id: "patent", ctx: "특허를 얻어냄", text: "특허를 얻어냈다" },
  { id: "patent", ctx: "특허를 얻는 데 실패함", text: "특허를 얻는 데 실패했다" },
  { id: "patent", ctx: "특허를 삼", text: "특허를 샀다" },
  { id: "patent", ctx: "특허를 봄", text: "특허를 보았다" },
  { id: "patent-medicine", ctx: "건강을 찾아 특효약에 의지함", text: "건강을 찾아 특효약에 의지했다" },
  { id: "patent-medicine", ctx: "특효약을 보거나 만듦", text: "특효약을 만들었다" },
  { id: "road", ctx: "좁고 험한 길에서 돌부리에 걸려 넘어짐", text: "좁고 험한 길에서 돌부리에 걸려 넘어졌다" },
  { id: "road", ctx: "제 길을 찾으려 애씀", text: "제 길을 찾으려 애썼다" },
  { id: "road", ctx: "풀과 꽃이 늘어선 오솔길을 걸음", text: "풀과 꽃이 늘어선 오솔길을 걸었다" },
  { id: "beggar", ctx: "늙고 쇠약한 거지를 봄", text: "늙고 쇠약한 거지를 보았다" },
  { id: "paunch", ctx: "큰 똥배를 봄", text: "큰 똥배를 보았다" },
  { id: "paunch", ctx: "쪼그라든 똥배를 봄", text: "쪼그라든 똥배를 보았다" },
  { id: "pauper", ctx: "제가 극빈자임을 꿈꿈", text: "제가 극빈자임을 꿈꿨다" },
  { id: "pauper", ctx: "극빈자들을 봄", text: "극빈자들을 보았다" },
  { id: "pawn-shop", ctx: "전당포에 들어감", text: "전당포에 들어갔다" },
  { id: "pawn-shop", ctx: "물건을 전당 잡힘", text: "물건을 전당 잡혔다" },
  { id: "pawn-shop", ctx: "여성이 전당포에 감", text: "여성이 전당포에 갔다" },
  { id: "pawn-shop", ctx: "전당 잡힌 물건을 되찾음", text: "전당 잡힌 물건을 되찾았다" },
  { id: "pawn-shop", ctx: "전당포를 봄", text: "전당포를 보았다" },
  // 지킴 — 이번 배치가 건드린 기존 상징의 옛 답이 그대로인가
  { id: "peach", ctx: "감과 복숭아를 먹음", text: "감과 복숭아를 먹었다" },
  { id: "peacock", ctx: "공작이 날며 춤춤", text: "공작이 날며 춤췄다" },
  { id: "peach", ctx: "복숭아를 보거나 먹음", text: "복숭아를 먹었다" },
  { id: "peach", ctx: "잎이 우거진 나무에 달린 복숭아를 봄", text: "잎이 우거진 나무에 달린 복숭아를 보았다" },
  { id: "peach", ctx: "마른 복숭아를 봄", text: "마른 복숭아를 보았다" },
  { id: "peach", ctx: "처녀가 무성한 나무에서 탐스러운 복숭아를 땀", text: "처녀가 무성한 나무에서 탐스러운 복숭아를 땄다" },
  { id: "peach", ctx: "복숭아가 설익고 옹이가 짐", text: "복숭아가 설익고 옹이가 졌다" },
  { id: "peacock", ctx: "공작 꿈을 꿈", text: "공작 꿈을 꾸었다" },
  { id: "peacock", ctx: "여성이 공작을 소유함", text: "여성이 공작을 소유했다" },
  { id: "peacock", ctx: "공작의 거친 울음소리를 들으며 화려한 깃털을 봄", text: "공작의 거친 울음소리를 들으며 화려한 깃털을 보았다" },
  // 지킴 — 이번 배치가 건드린 기존 상징의 옛 답이 그대로인가
  { id: "pear", ctx: "배를 먹음", text: "배를 먹었다" },
  { id: "pearl", ctx: "진주 꿈을 꿈", text: "진주 꿈을 꾸었다" },
  { id: "pearl", ctx: "애인이 진주를 선물함", text: "애인이 진주를 선물했다" },
  { id: "pearl", ctx: "진주를 잃거나 깨뜨림", text: "진주를 잃거나 깨뜨렸다" },
  { id: "pearl", ctx: "진주를 홀린 듯 바라봄", text: "진주를 홀린 듯 바라보았다" },
  { id: "pear", ctx: "우아한 나무에 달린 황금빛 열매를 감상함", text: "우아한 나무에 달린 배의 황금빛 열매를 감상했다" },
  { id: "pear", ctx: "배를 거둠", text: "배를 거두었다" },
  { id: "pear", ctx: "배를 저장함", text: "배를 저장했다" },
  { id: "pear", ctx: "배를 구움", text: "배를 구웠다" },
  { id: "pea", ctx: "완두콩을 먹음", text: "완두콩을 먹었다" },
  { id: "pea", ctx: "자라는 완두콩을 봄", text: "자라는 완두콩을 보았다" },
  { id: "pea", ctx: "완두콩을 심음", text: "완두콩을 심었다" },
  { id: "pea", ctx: "완두콩을 거둠", text: "완두콩을 거두었다" },
  { id: "pea", ctx: "통조림 완두콩 꿈을 꿈", text: "통조림 완두콩 꿈을 꾸었다" },
  { id: "pea", ctx: "마른 완두콩을 봄", text: "마른 완두콩을 보았다" },
  { id: "pea", ctx: "마른 완두콩을 먹음", text: "마른 완두콩을 먹었다" },
  { id: "pebble", ctx: "처녀가 조약돌 깔린 길 꿈을 꿈", text: "처녀가 조약돌 깔린 길 꿈을 꾸었다" },
  { id: "pebble", ctx: "조약돌 꿈을 꿈", text: "조약돌 꿈을 꾸었다" },
  { id: "pecan", ctx: "맛있는 피칸을 먹음", text: "맛있는 피칸을 먹었다" },
  { id: "pecan", ctx: "잎 사이에 자라는 피칸을 봄", text: "잎 사이에 자라는 피칸을 보았다" },
  { id: "pecan", ctx: "피칸이 썩은 정도만큼 사랑이나 사업에서 실패함", text: "피칸이 썩은 정도만큼 사랑이나 사업에서 실패했다" },
  { id: "pecan", ctx: "깨기 어렵고 열매가 작은 피칸을 봄", text: "깨기 어렵고 열매가 작은 피칸을 보았다" },
  { id: "pelican", ctx: "펠리컨 꿈을 꿈", text: "펠리컨 꿈을 꾸었다" },
  { id: "pelican", ctx: "펠리컨을 잡음", text: "펠리컨을 잡았다" },
  { id: "pelican", ctx: "펠리컨을 죽임", text: "펠리컨을 죽였다" },
  { id: "pelican", ctx: "펠리컨이 나는 것을 봄", text: "펠리컨이 나는 것을 보았다" },
  // 지킴 — 이번 배치가 건드린 기존 상징의 옛 답이 그대로인가
  { id: "prison", ctx: "옥에 갇혀 앉아 있음", text: "옥에 갇혀 앉아 있었다" },
  { id: "prison", ctx: "감옥에서 빠져나옴", text: "감옥에서 빠져나왔다" },
  { id: "pen", ctx: "펜 꿈을 꿈", text: "펜 꿈을 꾸었다" },
  { id: "pen", ctx: "펜이 써지지 않음", text: "펜이 써지지 않았다" },
  { id: "penalty", ctx: "벌금이나 처벌을 부과받음", text: "벌금이나 처벌을 부과받았다" },
  { id: "penalty", ctx: "벌금을 냄", text: "벌금을 냈다" },
  { id: "penalty", ctx: "벌금 내는 것을 피함", text: "벌금 내는 것을 피했다" },
  { id: "pencil", ctx: "연필 꿈을 꿈", text: "연필 꿈을 꾸었다" },
  { id: "pencil", ctx: "처녀가 연필로 글을 씀", text: "처녀가 연필로 글을 썼다" },
  { id: "pencil", ctx: "처녀가 쓴 글을 지움", text: "처녀가 연필로 쓴 글을 지웠다" },
  { id: "prison", ctx: "감옥 꿈을 꿈", text: "감옥 꿈을 꾸었다" },
  // 지킴 — 이번 배치가 건드린 기존 상징의 옛 답이 그대로인가
  { id: "coins", ctx: "금돈을 봄", text: "금돈을 보았다" },
  { id: "coins", ctx: "동전 꿈을 꿈", text: "동전 꿈을 꾸었다" },
  { id: "coins", ctx: "동전을 잃음", text: "동전을 잃었다" },
  { id: "coins", ctx: "동전을 찾음", text: "동전을 찾았다" },
  { id: "coins", ctx: "동전을 셈", text: "동전을 셌다" },
  { id: "pension", ctx: "연금을 받음", text: "연금을 받았다" },
  { id: "pension", ctx: "연금 신청에 실패함", text: "연금 신청에 실패했다" },
  { id: "pepper", ctx: "후추가 혀를 태움", text: "후추가 혀를 태웠다" },
  { id: "pepper", ctx: "자라는 붉은 고추를 봄", text: "자라는 붉은 고추를 보았다" },
  { id: "pepper", ctx: "쌓인 붉은 고추 꼬투리를 봄", text: "쌓인 붉은 고추 꼬투리를 보았다" },
  { id: "pepper", ctx: "검은 후추를 갊", text: "검은 후추를 갈았다" },
  { id: "pepper", ctx: "식탁 위 그릇에 담긴 후추를 봄", text: "식탁 위 그릇에 담긴 후추를 보았다" },
  { id: "pepper", ctx: "처녀가 음식에 후추를 뿌림", text: "처녀가 음식에 후추를 뿌렸다" },
  // 지킴 — 이번 배치가 건드린 기존 상징의 옛 답이 그대로인가
  { id: "sweat", ctx: "몸에 땀이 흐름", text: "몸에 땀이 흘렀다" },
  { id: "peppermint", ctx: "박하 꿈을 꿈", text: "박하 꿈을 꾸었다" },
  { id: "peppermint", ctx: "자라는 박하를 봄", text: "자라는 박하를 보았다" },
  { id: "peppermint", ctx: "박하 향이 나는 음료를 즐김", text: "박하 향이 나는 음료를 즐겼다" },
  { id: "peppermint", ctx: "처녀가 박하 향이 나는 음료를 즐기는 꿈을 꿈", text: "처녀가 박하 향이 나는 음료를 즐기는 꿈을 꾸었다" },
  { id: "perfume", ctx: "향수를 들이마심", text: "향수를 들이마셨다" },
  { id: "perfume", ctx: "몸이나 옷에 향수를 뿌림", text: "몸이나 옷에 향수를 뿌렸다" },
  { id: "perfume", ctx: "향수에 취할 만큼 짓눌림", text: "향수에 취할 만큼 짓눌렸다" },
  { id: "perfume", ctx: "향수를 쏟음", text: "향수를 쏟았다" },
  { id: "perfume", ctx: "향수병을 깨뜨림", text: "향수병을 깨뜨렸다" },
  { id: "perfume", ctx: "향수를 증류함", text: "향수를 증류했다" },
  { id: "perfume", ctx: "처녀가 목욕물에 향을 더하는 꿈을 꿈", text: "처녀가 목욕물에 향을 더하는 꿈을 꾸었다" },
  { id: "perfume", ctx: "남자에게 향수를 선물받음", text: "남자에게 향수를 선물받았다" },
  { id: "pest", ctx: "온갖 성가심에 시달리는 꿈을 꿈", text: "온갖 골칫거리에 시달리는 꿈을 꾸었다" },
  { id: "pest", ctx: "남이 그렇게 시달리는 것을 봄", text: "남이 골칫거리에 시달리는 것을 보았다" },
  { id: "petticoat", ctx: "새 속치마를 봄", text: "새 속치마를 보았다" },
  { id: "petticoat", ctx: "때묻거나 찢어진 속치마를 봄", text: "때묻거나 찢어진 속치마를 보았다" },
  { id: "petticoat", ctx: "처녀가 비단이나 깨끗한 속치마를 입는 꿈을 꿈", text: "처녀가 비단이나 깨끗한 속치마를 입는 꿈을 꾸었다" },
  { id: "petticoat", ctx: "처녀가 옷 입다 속치마를 빠뜨린 것을 알아챔", text: "처녀가 옷 입다 속치마를 빠뜨린 것을 알아챘다" },
  { id: "petticoat", ctx: "모임이나 걷는 중에 속치마가 흘러내리는 것을 봄", text: "모임이나 걷는 중에 속치마가 흘러내리는 것을 보았다" },
  { id: "pewter", ctx: "백랍 꿈을 꿈", text: "백랍 꿈을 꾸었다" },
  { id: "phantom", ctx: "환영이 저를 쫓아옴", text: "환영이 저를 쫓아왔다" },
  { id: "phantom", ctx: "환영이 저에게서 달아남", text: "환영이 저에게서 달아났다" },
  { id: "pheasant", ctx: "꿩 꿈을 꿈", text: "꿩 꿈을 꾸었다" },
  { id: "pheasant", ctx: "꿩을 먹음", text: "꿩을 먹었다" },
  { id: "pheasant", ctx: "꿩을 쏨", text: "꿩을 쏘았다" },
  { id: "phosphorus", ctx: "인이 빛나는 것을 봄", text: "인이 빛나는 것을 보았다" },
  { id: "phosphorus", ctx: "처녀가 인이 빛나는 꿈을 꿈", text: "처녀가 인이 빛나는 꿈을 꾸었다" },
  // 지킴 — 이번 배치가 건드린 기존 상징의 옛 답이 그대로인가
  { id: "doctor", ctx: "의사를 사사로이 만남", text: "의사를 사사로이 만났다" },
  { id: "doctor", ctx: "의사에게 진찰을 받음", text: "의사에게 진찰을 받았다" },
  { id: "photograph", ctx: "사진들을 봄", text: "사진들을 보았다" },
  { id: "photograph", ctx: "애인의 사진을 받음", text: "애인의 사진을 받았다" },
  { id: "photograph", ctx: "기혼자가 남의 사진을 지님", text: "기혼자가 남의 사진을 지녔다" },
  { id: "photograph", ctx: "제 사진을 찍음", text: "제 사진을 찍었다" },
  { id: "doctor", ctx: "처녀가 의사 꿈을 꿈", text: "처녀가 의사 꿈을 꾸었다" },
  { id: "doctor", ctx: "아픈 처녀가 의사 꿈을 꿈", text: "아픈 처녀가 의사 꿈을 꾸었다" },
  { id: "doctor", ctx: "의사가 몹시 근심스러워 보임", text: "의사가 몹시 근심스러워 보였다" },
  { id: "piano", ctx: "피아노를 봄", text: "피아노를 보았다" },
  { id: "piano", ctx: "피아노에서 감미로운 화음을 들음", text: "피아노에서 감미로운 화음을 들었다" },
  { id: "piano", ctx: "귀에 거슬리는 음악이 연주됨", text: "피아노에서 귀에 거슬리는 음악이 연주되었다" },
  { id: "piano", ctx: "슬프고 애처로운 음악을 들음", text: "피아노에서 슬프고 애처로운 음악을 들었다" },
  { id: "piano", ctx: "피아노가 부서지고 음이 안 맞는 것을 봄", text: "피아노가 부서지고 음이 안 맞는 것을 보았다" },
  { id: "piano", ctx: "낡은 구식 피아노를 봄", text: "낡은 구식 피아노를 보았다" },
  { id: "piano", ctx: "처녀가 어렵고도 황홀한 곡을 연주함", text: "처녀가 피아노로 어렵고도 황홀한 곡을 연주했다" },
  { id: "pickaxe", ctx: "곡괭이 꿈을 꿈", text: "곡괭이 꿈을 꾸었다" },
  { id: "pickaxe", ctx: "부러진 곡괭이를 봄", text: "부러진 곡괭이를 보았다" },
  { id: "pickle", ctx: "피클 꿈을 꿈", text: "피클 꿈을 꾸었다" },
  { id: "pickle", ctx: "처녀가 피클을 먹는 꿈을 꿈", text: "처녀가 피클을 먹는 꿈을 꾸었다" },
  { id: "pickle", ctx: "처녀가 피클을 먹거나 몹시 먹고 싶어함", text: "처녀가 피클을 몹시 먹고 싶어했다" },
  { id: "pickle", ctx: "상한 피클을 봄", text: "상한 피클을 보았다" },
  { id: "pickpocket", ctx: "소매치기 꿈을 꿈", text: "소매치기 꿈을 꾸었다" },
  { id: "pickpocket", ctx: "처녀가 소매치기를 당함", text: "처녀가 소매치기를 당했다" },
  { id: "pickpocket", ctx: "처녀가 소매치기 짓을 함", text: "처녀가 소매치기 짓을 했다" },
  { id: "picnic", ctx: "소풍에 참석함", text: "소풍에 참석했다" },
  { id: "picnic", ctx: "소풍 꿈을 꿈", text: "소풍 꿈을 꾸었다" },
  { id: "picnic", ctx: "소풍에서 폭풍우나 방해되는 일이 생김", text: "소풍에서 폭풍우가 몰아쳤다" },
  // 지킴 — 이번 배치가 건드린 기존 상징의 옛 답이 그대로인가
  { id: "docks", ctx: "부두에 있음", text: "부두에 있었다" },
  { id: "painting", ctx: "아름다운 그림들을 봄", text: "아름다운 그림들을 보았다" },
  { id: "painting", ctx: "그림들이 눈앞에 나타남", text: "그림들이 눈앞에 나타났다" },
  { id: "painting", ctx: "그림을 만듦", text: "그림을 만들었다" },
  { id: "painting", ctx: "그림을 없앰", text: "그림을 없앴다" },
  { id: "painting", ctx: "그림을 삼", text: "그림을 샀다" },
  { id: "painting", ctx: "살아있는 나무에서 제 모습이 나타났다 사라지는 것을 봄", text: "살아있는 나무에서 제 모습이 나타났다 사라지는 것을 보았다" },
  { id: "painting", ctx: "옛 거장과 현대 거장의 걸작들에 둘러싸임", text: "옛 거장과 현대 거장의 걸작들에 둘러싸였다" },
  { id: "docks", ctx: "부두 위에 섬", text: "부두 위에 섰다" },
  { id: "docks", ctx: "부두에 닿으려다 실패함", text: "부두에 닿으려다 실패했다" },
  // 지킴 — 이번 배치가 건드린 기존 상징의 옛 답이 그대로인가
  { id: "pig", ctx: "살지고 튼튼한 돼지를 봄", text: "살지고 튼튼한 돼지를 보았다" },
  { id: "pig", ctx: "여윈 돼지를 봄", text: "여윈 돼지를 보았다" },
  { id: "pie", ctx: "파이를 먹음", text: "파이를 먹었다" },
  { id: "pie", ctx: "처녀가 파이를 만드는 꿈을 꿈", text: "처녀가 파이를 만드는 꿈을 꾸었다" },
  { id: "pig", ctx: "진흙탕에서 뒹구는 돼지들을 봄", text: "진흙탕에서 뒹구는 돼지들을 보았다" },
  { id: "pig", ctx: "처녀가 진흙탕 돼지 꿈을 꿈", text: "처녀가 진흙탕 돼지 꿈을 꾸었다" },
  // 지킴 — 이번 배치가 건드린 기존 상징의 옛 답이 그대로인가
  { id: "dove", ctx: "비둘기가 짝을 짓고 둥지를 지음", text: "비둘기가 짝을 짓고 둥지를 지었다" },
  { id: "dove", ctx: "흰 비둘기를 봄", text: "하얀 비둘기를 보았다" },
  { id: "dove", ctx: "사격 시합에 쓰이는 비둘기를 봄", text: "사격 시합에 쓰이는 비둘기를 보았다" },
  { id: "dove", ctx: "비둘기가 나는 것을 봄", text: "비둘기가 나는 것을 보았다" },
  { id: "pilgrim", ctx: "순례자 꿈을 꿈", text: "순례자 꿈을 꾸었다" },
  { id: "pilgrim", ctx: "제가 순례자임을 꿈꿈", text: "제가 순례자임을 꿈꿨다" },
  { id: "pilgrim", ctx: "처녀에게 순례자가 다가옴", text: "처녀에게 순례자가 다가왔다" },
  { id: "pilgrim", ctx: "순례자가 처녀를 떠남", text: "순례자가 처녀를 떠났다" },
  { id: "pill", ctx: "알약을 먹음", text: "알약을 먹었다" },
  { id: "pill", ctx: "남에게 알약을 줌", text: "남에게 알약을 주었다" },
];

let notFound = 0;
let wrongCtx = 0;

for (const c of CASES) {
  const result = matchDream(c.text);
  const hit = result.matched.find((m) => m.id === c.id);
  if (!hit) {
    console.log(`✗ 안 걸림   [${c.id}] 「${c.text}」`);
    notFound++;
    continue;
  }
  if (hit.meaning.context !== c.ctx) {
    console.log(
      `✗ 다른 뜻   [${c.id}] 「${c.text}」\n              바란 것: ${c.ctx}\n              나온 것: ${hit.meaning.context}`,
    );
    wrongCtx++;
    continue;
  }
  console.log(`  OK        [${c.id}] ${c.ctx}`);
}

console.log(`\n시험 ${CASES.length}건 · 안 걸림 ${notFound}건 · 다른 뜻 ${wrongCtx}건`);
process.exit(notFound + wrongCtx > 0 ? 1 : 0);
