// v2 사전(원문 재구축) 전용 영어 매칭 키. `dream-contexts-ko.v2.ts`의 영어판.
// `scripts/build-dream-match-tables-v2.mjs`가 만든다.

export const CONTEXT_EN_V2: Record<string, string> = {
  "well::우물을 파서 물을 봄": "dug digging",
  "well::우물이 저절로 부서짐": "collapsed crumbled broke broken",
  "well::우물물이 끓어 넘침": "boiling boiled overflowing overflowed bubbling",
  "well::우물이 말라붙음": "dried parched bone",
  "well::우물에 몸을 비춰 봄": "reflection reflected mirror",
  "well::몸이 우물에 빠짐": "fell falling drowning drowned",
  "well::방이 우물 속에 있음": "room bedroom",
  "well::길어 올린 우물물이 맑음": "clear pure transparent crystal",
  "well::길어 올린 우물물이 흐림": "murky cloudy turbid dirty",
  "well::우물물에 진흙이 섞여 있음": "mud muddy silt sludge",
  "well::우물이 마르려 함": "drying shrinking receding sinking",
  "well::우물 안에 물고기가 있음": "fish carp swimming",
  "well::우물을 들여다보는데 소리가 남": "sound voice echo noise",
  "well::우물 속에 엎드려 숨음": "hiding hid crouched hidden",
  "well::취해서 우물에 빠짐": "drunk drunken intoxicated",
  "well::집이 우물 속에 있음": "house home",
  "well::사람이 우물에서 나온다고 말함": "emerged emerging climbed",
  "well::우물을 치거나 새로 팜": "cleaned cleaning repaired renovated",
  "well::그릇이 우물에 떨어짐": "bowl dish jar dropped",
  "well::불을 잡고 우물을 태움": "fire burning burned burnt",
  "moon::달이 막 떠오름": "rose risen appeared",
  "moon::달빛이 몸을 비춤": "shone shining bathed lit",
  "moon::달이 떨어짐": "fell falling dropped",
  "moon::달이 어둑하게 흐림": "dim dark hazy faint clouded",
  "moon::달이 막 떠오르려 함": "rising emerging beginning",
  "moon::해와 달이 한자리에서 만남": "sun solar together",
  "moon::달이 산에 걸림": "mountain peak hung caught",
  "moon::달을 등에 지거나 품에 안음": "carried back embraced held",
  "moon::달을 삼킴": "swallowed swallow ate",
  "moon::달에 절하여 예를 올림": "bowed bowing worship prayed",
  "moon::달이 품 안으로 들어옴": "entered entering bosom chest",
  "moon::달에 절하고 향을 사름": "incense burned burning",
  "cart::수레가 다리와 길 위를 지나감": "bridge road crossing passed",
  "cart::관을 쓰고 수레에 오름": "cap crown wearing",
  "cart::수레가 부서져 깨짐": "broke broken shattered wrecked",
  "cart::짐을 실은 수레가 일어나지 못함": "loaded heavy cargo burden",
  "cart::수레를 몰고 나다님": "drove driving riding around",
  "cart::수레가 잘 굴러감": "smoothly rolled rolling easily",
  "cart::수레가 나아가지 않음": "stuck stopped budge halted",
  "cart::수레가 대문 안으로 들어옴": "gate courtyard house entered",
  "cart::앓는 사람이 수레에 오름": "sick ill patient",
  "cart::흰 말이 끄는 수레를 몰음": "white horse",
  "rice-plant::스스로 밭에 벼를 심음": "planted planting sowed sowing",
  "rice-plant::몸이 벼 속에 들어가 있음": "inside among surrounded buried",
  "rice-plant::밭의 벼를 베어 거둠": "harvest harvested reaped cut",
  "rice-plant::지붕 위에 벼가 자람": "roof rooftop",
  "rice-plant::볏모가 잘 여묾": "ripened ripe mature full",
  "rice-plant::벼를 봄": "saw looked",
  "rice-plant::벼와 곡식을 얻음": "grain received obtained gained",
  "rice-plant::벼를 얻었다가 갑자기 잃음": "lost losing suddenly gone",
  "illness::병들어 누웠는데 남이 부축해 줌": "helped supported lifted nursed",
  "illness::병이 위중함": "grave serious critical severe",
  "illness::자기가 병듦": "myself own personally",
  "illness::병자가 노래함": "singing sang song",
  "illness::병자가 울고 웃음": "crying laughing tears laughed",
  "illness::병자가 자리에서 일어남": "rose recovered better standing",
  "illness::병자가 수레에 실림": "cart wagon carried loaded",
  "basin::동이를 봄": "saw looked",
  "basin::동이의 밑바닥이 빠짐": "bottom broke hole cracked",
  "basin::동이 안으로 들어감": "inside entered climbed",
  "basin::크고 작은 동이를 함께 봄": "large small several both",
  "basin::동이를 얻음": "received got obtained gained",
  "dead-person::죽은 사람이 욺": "crying wept weeping",
  "dead-person::죽은 사람이 일어서 있음": "standing stood upright",
  "dead-person::죽은 사람이 품에서 욺": "arms embrace bosom held",
  "dead-person::죽은 사람이 되살아남": "revived resurrected alive again",
  "dead-person::죽은 사람이 음식을 먹음": "food eating ate meal",
  "wind::사나운 바람이 몰아침": "fierce raging violent savage",
  "wind::바람이 사람의 옷자락을 불어 젖힘": "clothes sleeve skirt blew",
  "wind::갑자기 큰바람이 붊": "suddenly sudden strong huge",
  "wind::바람이 울부짖듯 소리를 냄": "howling wailing sound noise",
  "wind::바람이 불어 집이 흔들림": "house shook shaking building",
  "river::강과 바다가 넘쳐 불어남": "sea ocean overflow flooded swelling",
  "river::강물에 모래와 돌이 있음": "sand pebbles stones rocks",
  "river::불이 강물을 태움": "fire flames burning burned",
  "river::배를 타고 강을 건넘": "boat crossed crossing ferry",
  "storehouse::왕과 제후의 곳간에 들어감": "king royal palace lord",
  "storehouse::창고를 새로 지어 세움": "built building constructed erected",
  "storehouse::창고 안으로 들어감": "inside entered",
  "storehouse::창고가 무너짐": "collapsed crumbled ruined",
  "fine-toothed-comb::남이 참빗을 줌": "gave gift handed offered",
  "fine-toothed-comb::참빗을 봄": "saw looked",
  "fine-toothed-comb::참빗을 얻음": "obtained found acquired picked",
  "meat::날고기를 먹음": "raw bloody fresh",
  "meat::익힌 고기를 먹음": "cooked grilled boiled roasted",
  "meat::저절로 죽은 짐승의 고기를 먹음": "carrion rotten dead animal",
  "thief::무리를 이끌고 도적을 무찌름": "defeated led troops fought",
  "thief::도적이 스스로 옥에 들어감": "prison jail surrendered",
  "thief::도적을 쫓아가는 것을 봄": "chasing chased pursuing",
  "bamboo-shoot::죽순을 꺾어 집으로 가져옴": "picked broke brought carried",
  "bamboo-shoot::죽순을 봄": "saw looked growing",
  "blue-clothing::푸른 옷을 입음": "wore wearing dressed",
  "blue-clothing::남과 함께 푸른 옷을 입음": "together others everyone",
  "duck::오리가 거위와 함께 헤엄침": "goose geese swimming together",
  "duck::오리를 잡음": "caught catching grabbed",
  "forest::동산의 숲이 우거짐": "lush dense thick overgrown",
  "forest::숲속에 앉거나 누움": "sat sitting lay lying rested",
  "manure::땅을 쓸어 거름을 치움": "swept cleared removed cleaned",
  "manure::거름 흙이 수북이 쌓임": "piled heap mound stacked",
  "moving-house::남의 새 집으로 옮겨 듦": "new clean bright fine",
  "moving-house::헐고 낡은 집으로 옮겨 감": "old shabby dilapidated ruined",
  "rainbow::붉은 무지개를 봄": "red crimson scarlet",
  "rainbow::검은 무지개를 봄": "black dark",
  "shrimp::새우가 물고기로 변함": "fish became turned changed",
  "shrimp::새우와 조개가 울며 달아남": "clam fleeing fled",
  "clothing::옷이 진흙으로 더러워짐": "mud muddy dirtied",
  "clothing::적삼이 진흙으로 더러워짐": "undershirt jacket garment",
  "clothing::남에게 옷을 줌": "someone another else",
  "clothing::귀인이 옷을 줌": "noble nobleman dignitary official",
  "clothing::옷을 새것으로 바꿔 입음": "changed changing swapped replaced",
  "clothing::새 도포를 입음": "cloak mantle wrap",
  "clothing::비단에 수놓은 옷을 입음": "silk embroidered brocade",
  "clothing::옷을 빨아 물들임": "dyed dyeing dye washed",
  "clothing::도롱이를 걸침": "straw raincoat cape",
  "clothing::옷이 기름에 더러워짐": "oil grease greasy stained",
  "clothing::옷이 갑자기 해짐": "torn frayed ragged tattered suddenly",
  "clothing::새 옷에 쌀을 모아 담음": "rice grain gathered",
  "clothing::옷감을 마름질해 지어 입음": "sewed sewing tailored stitched",
  "clothing::아내가 남편의 옷을 입음": "wife husband",
  "clothing::여자가 옷을 차려입음": "woman dressed up adorned",
  "clothing::남과 옷을 함께 입음": "shared together same",
  "clothing::옷을 잃어버림": "lost losing missing",
  "sky::하늘의 문이 열림": "gate door opened opening",
  "sky::하늘의 빛이 몸을 비춤": "shone shining ray beam",
  "sky::하늘이 맑게 갬": "cleared clearing sunny",
  "sky::하늘이 환하게 밝음": "bright brightly glowing radiant",
  "sky::얼굴을 들어 하늘을 바라봄": "looked gazing gazed upward",
  "sky::하늘의 문이 붉음": "reddish crimson scarlet",
  "sky::용을 타고 하늘에 오름": "dragon rode riding",
  "sky::하늘에 올라 아내를 구함": "wife bride sought",
  "sky::하늘에서 물건을 가져옴": "brought took something object",
  "sky::날아서 하늘로 오름": "flew flying flight wings",
  "sky::하늘에 올랐다가 지붕 위에 오름": "roof rooftop",
  "sky::하늘이 갈라짐": "split cracked torn apart",
  "sky::하늘이 더욱 넉넉하고 풍성함": "vast abundant boundless immense",
  "sky::하늘을 두루 돌아다님": "wandered roamed traveled around",
  "blood::손발에서 고름과 피가 나옴": "pus hands feet limbs",
  "blood::피가 침상에 묻어 있음": "bedding sheets mattress",
  "blood::소뿔에 피가 묻어 있음": "ox horn cow bull",
  "blood::칼에 다쳐 피가 남": "knife blade sword dagger",
  "blood::피가 옷을 적심": "clothes soaked drenched shirt",
  "blood::서로 싸우다 피를 봄": "fight fought fighting quarrel",
  "blood::상처에서 피가 남": "wound injury scar",
  "blood::베이고 찔려 피를 봄": "stabbed pierced pricked slashed",
  "blood::몸에서 피가 흐르는 것을 봄": "flowing streamed pouring body",
  "buddha::부처께 절하니 부처가 움직이려 함": "bowed bowing moved stirred",
  "buddha::부처가 성을 냄": "angry anger wrathful furious",
  "buddha::여러 부처와 보살을 봄": "many several bodhisattvas multiple",
  "buddha::신과 부처를 그림": "painted painting drew drawing",
  "buddha::마루 위에 신과 부처가 있음": "floor hall wooden",
  "buddha::신과 부처가 형체를 이루지 못함": "shapeless formless blurred indistinct",
  "buddha::신과 부처를 바라봄": "gazed staring watching",
  "buddha::부처가 사람과 말을 나눔": "spoke talking conversation words",
  "bed-curtain::침상 휘장을 바꿈": "changed replaced",
  "bed-curtain::침상 휘장을 활짝 펼침": "spread wide drawn open",
  "bed-curtain::침상 휘장을 새로 침": "new hung hanging",
  "bed-curtain::침상 휘장이 문 밖으로 나감": "outside door outdoors",
  "bed-curtain::침상 휘장을 거두어 바꿈": "down removed gathered",
  "bed-curtain::침상 휘장이 찢어지고 상함": "torn tattered damaged ripped",
  "bed-curtain::침상 휘장을 빨아 씻음": "washed washing cleaned",
  "ground::땅이 흔들려 움직임": "shook shaking earthquake trembled",
  "ground::땅이 갈라짐": "split cracked crack fissure",
  "ground::밭과 땅을 평평하게 고름": "leveled flattened field smoothed",
  "ground::땅이 높고 낮아 고르지 않음": "uneven bumpy sloping rough",
  "ground::땅속에서 검은 기운이 올라옴": "black dark vapor smoke rising",
  "ground::집 마루 위의 땅이 꺼짐": "sank collapsed caved floor",
  "drum::북을 침": "beat beating struck hitting",
  "drum::종과 북이 크게 울림": "bell bells loudly echoing",
  "drum::북을 쳐 소리가 남": "sounded noise",
  "drum::북의 아름다운 소리를 들음": "beautiful lovely pleasant heard",
  "drum::북을 보아도 울리지 않음": "silent soundless quiet nothing",
  "weeping::남과 함께 소리 내어 욺": "together someone both",
  "weeping::소리를 놓아 크게 욺": "loudly aloud wailed bawling",
  "weeping::먼 데서 온 사람이 슬피 욺": "sadly sorrowfully stranger far away",
  "weeping::침상 위에서 욺": "bed bedside lying",
  "weeping::이를 드러내고 욺": "teeth bared showing",
  "road::사방으로 길이 뚫려 있음": "directions crossroads everywhere",
  "road::길에서 재물을 주움": "picked up found money treasure",
  "road::길이 진흙탕이고 가시덤불이 우거짐": "muddy thorns brambles overgrown",
  "road::큰길이 무너져 내려앉음": "collapsed caved sank crumbled",
  "silk::채색 비단을 남에게 줌": "colored colorful multicolored",
  "silk::귀인이 비단을 내려 줌": "noble nobleman dignitary bestowed",
  "silk::남이 명주 비단을 줌": "received got",
  "silk::남에게 비단을 줌": "handed gave away",
  "flower::남과 꽃을 나누어 가짐": "shared sharing divided together",
  "flower::마른 나무에 꽃이 핌": "dead tree withered bare branch bloomed",
  "flower::배 위에서 꽃을 봄": "boat ship deck",
  "man::남자와 몸을 섞음": "sex intercourse slept lovemaking",
  "man::남자가 알몸으로 있음": "naked nude undressed bare",
  "man::남자가 여승으로 변함": "nun turned into transformed became",
  "thunder::우레가 크게 침": "loud loudly crashed struck",
  "thunder::우렛소리가 두렵게 들림": "frightening scary afraid terrified",
  "thunder::우레가 땅에서 울림": "ground below beneath",
  "armor::갑옷과 투구가 몸을 감쌈": "helmet wrapped covered whole body",
  "armor::갑옷을 입고 칼을 짚음": "sword blade leaning holding",
  "book::여러 빛깔의 경서를 봄": "colored colorful multicolored several",
  "book::책상 위에 책이 있음": "desk table",
  "donkey::나귀를 타고 감": "rode riding mounted",
  "donkey::나귀를 잡음": "caught grabbed seized",
  "fruit-tree::문 안에 과일나무가 자람": "gate courtyard growing grew inside",
  "fruit-tree::과일나무에 열매가 많이 익음": "ripe ripened laden abundant",
  "long-journey::먼 길을 오가며 다님": "forth coming going wandering",
  "long-journey::텅 비고 사람이 없는 먼 곳": "empty deserted nobody desolate",
  "mule::노새를 타고 감": "rode riding mounted",
  "mule::노새를 잡음": "caught grabbed seized",
  "rabbit::토끼 무리가 하늘로 오름": "sky rose flew group flock",
  "rabbit::살아 있는 토끼가 동산에 있음": "hill garden alive living",
  "shrine::신을 모신 사당에 들어감": "entered walked inside enshrined",
  "shrine::사당이 넓고 큼": "large spacious wide grand",
  "snake::뱀이 문 안으로 들어옴": "door doorway gate entrance threshold",
  "snake::뱀이 부뚜막에 들어옴": "stove kitchen hearth furnace",
  "snake::뱀이 용으로 변함": "dragon dragons ascended transformed",
  "snake::뱀이 사람을 죽임": "killed kill killing slain",
  "snake::뱀이 사람에게 덤벼듦": "lunged attacked charged bit striking",
  "snake::뱀이 품속으로 들어옴": "bosom chest clothes hugged",
  "snake::뱀이 물속을 헤엄쳐 감": "swimming swam water river stream",
  "snake::뱀이 사람을 따라감": "followed following chased pursued",
  "snake::뱀이 곡도로 들어감": "hole burrow cave tunnel",
  "snake::뱀이 몸을 휘감음": "coiled wrapped wound around squeezed",
  "snake::뱀이 여럿 몰려 있음": "many several swarm nest lots",
  "snake::뱀이 붉거나 검음": "red black crimson dark",
  "snake::뱀이 푸름": "green greenish emerald",
  "snake::뱀이 누렇거나 흼": "yellow white pale golden",
  "snake::뱀이 다가오고 새가 달려옴": "bird birds sparrow flying",
  "snake::거북과 뱀이 함께 있음": "turtle tortoise",
  "sun::해가 막 떠오름": "rose rising dawn daybreak morning",
  "sun::햇빛이 몸을 비춤": "shone body skin rays warm",
  "sun::해가 떨어짐": "setting sank west dusk twilight",
  "sun::해가 어둑하게 흐림": "dim dull gloomy faint hazy",
  "sun::해가 막 떠오르려 함": "almost horizon barely emerging",
  "sun::해와 달이 한자리에서 만남": "moon together alongside crescent",
  "sun::해가 산에 걸림": "mountain peak hung ridge",
  "sun::해를 등에 지거나 품에 안음": "back shoulders carried bore",
  "sun::해를 삼킴": "swallowed swallow ate devoured",
  "sun::해에 절하여 예를 올림": "bowed bowing worshipped knelt",
  "sun::햇빛이 집 안으로 들어옴": "house room window indoors",
  "sun::해가 처음 떠오르는데 구름 한 점 없음": "cloudless spotless pure serene",
  "sun::해가 떠서 빛이 남": "shining brilliant dazzling radiance glowed",
  "sun::구름이 걷히고 해가 떠오름": "cleared parted lifted broke",
  "sun::해가 품 안으로 들어옴": "bosom chest embraced hugged",
  "sun::해가 구름에 갑자기 가려짐": "covered hidden obscured blocked suddenly",
  "city-wall::궁성이 막힘": "blocked barred palace shut sealed",
  "city-wall::성에 오르는데 남이 끌어 줌": "pulled helped lifted assisted",
  "city-wall::성에 올랐다가 붙잡힘": "caught seized captured arrested",
  "city-wall::성곽이 넓고 큼": "vast huge wide enormous grand",
  "city-wall::성 안을 돌아다님": "wandering wandered strolling roaming inside",
  "city-wall::성문을 나섬": "gate exited leaving outside",
  "city-wall::이어진 성이 푸른빛을 띰": "green blue connected stretching",
  "city-wall::붉은 성곽에 오름": "crimson scarlet vermilion",
  "city-wall::성 위에 집을 지음": "house built building home",
  "outhouse::뒷간 안에 머물러 있음": "stayed standing sitting remained inside",
  "outhouse::뒷간에 빠졌다가 밖으로 나옴": "escaped climbed emerged crawled out",
  "outhouse::뒷간에 빠져 나오지 못함": "stuck trapped unable sinking couldn't",
  "outhouse::뒷간 지붕 위에 누움": "roof lying lay top",
  "outhouse::뒷간 안이 바싹 말라 있음": "dry dried parched empty",
  "outhouse::뒷간을 새로 지음": "built new building rebuilt",
  "outhouse::뒷간을 쳐서 치움": "cleaned emptied cleared scooped",
  "outhouse::뒷간에 가서 똥오줌 속에 있음": "excrement urine feces filth",
  "outhouse::뒷간에 똥이 넘침": "overflowing overflowed spilling full",
  "sheep::양을 끌고 집으로 돌아옴": "home leading brought returned",
  "sheep::양이 돼지처럼 걸어감": "pig walked waddling",
  "sheep::양이 몸을 긁음": "scratching scratched itching rubbing",
  "sheep::양을 타고 거리로 나감": "riding rode street town",
  "sheep::어미 양과 새끼 양을 봄": "mother baby young lambs",
  "sheep::양을 잡거나 때림": "killed beat slaughtered hit",
  "sheep::양이 수레를 끎": "cart wagon pulling carriage",
  "pig::돼지를 잡음": "caught killed slaughtered butchered",
  "pig::돼지가 저절로 죽음": "died dead sick naturally itself",
  "pig::돼지가 사람으로 변함": "human person transformed turned",
  "pig::양이 돼지처럼 걸어감": "sheep lamb walking",
  "pig::돼지가 몸을 긁음": "scratching scratched itching rubbing",
  "turtle::거북이 우물이나 집으로 들어옴": "well house home yard entered",
  "turtle::거북과 뱀이 함께 있음": "snake serpent together",
  "turtle::거북을 봄": "saw seeing looked spotted",
  "turtle::거북을 잡음": "caught catching grabbed held",
  "turtle::거북을 죽임": "killed kill dead",
  "barley::보리를 봄": "saw seeing looked",
  "barley::크고 작은 보리를 봄": "big small large little",
  "barley::쌀과 보리가 나란히 놓임": "rice laid placed piled",
  "barley::쌀과 보리 위에 앉거나 누움": "sat sitting lay lying",
  "rain::비가 그쳐 흩어짐": "stopped ceased dispersed clearing",
  "rain::궂은비가 내려 어둑함": "drizzle dreary gloomy grey dismal",
  "rain::길을 가다 비를 만남": "road walking journey path caught",
  "rain::큰비가 쏟아짐": "pouring heavy torrential downpour",
  "thief-2::도둑을 쫓아 저자에 들어가 나오지 못함": "chasing chased market pursued",
  "thief-2::억센 도둑이 집에 들어옴": "fierce strong house intruder broke",
  "thief-2::도둑과 함께 길을 감": "together walked along accompanied",
  "thief-2::자기가 도둑이 됨": "myself became stealing stole",
  "fight::집안 사람끼리 다툼": "family household relatives parents",
  "fight::여자들이 서로 때림": "women woman wives ladies",
  "fight::형제가 서로 때림": "brothers brother siblings",
  "monk::법사가 법좌에 오름": "dharma seat preaching pulpit ascended",
  "monk::스님이 사람에게 경 읽기를 가르침": "teaching taught reading sutra learn",
  "monk::스님과 비구니가 경을 봄": "nun nuns together",
  "sun-and-moon::불이 해와 달을 태움": "fire burning burned flames",
  "sun-and-moon::배 위에서 해와 달을 봄": "boat deck watching aboard",
  "sun-and-moon::배를 타고 해와 달을 지나감": "sailed passed crossing past",
  "beard::수염이 희어져 빠짐": "white grey turned falling",
  "beard::빠졌던 수염이 다시 남": "grew back again regrew new",
  "bell::종과 경쇠가 소리를 냄": "chime chimes stone sounding clear",
  "bell::종과 북이 크게 울림": "drum drums loud thunderous booming",
  "farming::산속에서 농사를 지음": "mountain mountains hills",
  "farming::남에게 밭 갈고 씨 뿌리는 법을 가르침": "teaching taught showed others",
  "flute::남이 피리를 줌": "gave given received gift",
  "flute::피리를 붊": "played playing blowing blew",
  "marketplace::부부가 함께 시장에 들어감": "wife husband couple together",
  "marketplace::시장에 사람이 하나도 없음": "empty deserted nobody abandoned",
  "monkey::산 원숭이를 봄": "wild mountain forest",
  "monkey::흰 원숭이를 봄": "white pale snowy",
  "rock::너럭바위가 편안하고 든든함": "flat comfortable solid steady broad",
  "rock::바위에 오름": "climbed climbing ascended top",
  "shooting-an-arrow::내가 남을 쏨": "aimed aiming target someone",
  "shooting-an-arrow::남이 나를 쏨": "hit struck wounded pierced",
  "house::불이 제 집을 태움": "fire burning burned burnt ablaze",
  "house::집 안에 불빛이 있음": "light lit glowing lamp bright",
  "house::남의 집을 사들임": "bought buying purchased",
  "house::성 위에 집을 지음": "castle fortress wall built building",
  "house::집 지붕 위에 오름": "climbed climbing onto top",
  "house::올라간 지붕이 부서짐": "collapsed broke broken crumbled",
  "house::지붕을 새로 덮음": "thatch thatched tiles retiled shingles",
  "house::집을 새로 고침": "repaired renovated remodeled fixed",
  "house::바람에 집이 흔들림": "wind shaking shook swayed storm",
  "house::살던 집에서 나옴": "left leaving moved away departed",
  "house::집을 남에게 저당 잡힘": "mortgage mortgaged pawned collateral",
  "house::집을 팔거나 저당 잡힘": "sold selling sell",
  "house::집에 사람이 하나도 없음": "empty nobody deserted abandoned",
  "house::지붕 위로 배가 지나감": "boat ship sailing sailed",
  "house::남과 집을 두고 다툼": "quarrel dispute argued neighbor stranger",
  "house::부인과 집을 두고 다툼": "wife spouse marital",
  "house::집 마당이 꺼져 내려앉음": "yard courtyard sank sinking caved",
  "house::시골집을 손보아 고침": "countryside village hometown rural",
  "dragon::용을 타고 하늘에 오름": "sky clouds heavens skyward",
  "dragon::용을 타고 물에 들어감": "water river sea ocean submerged",
  "dragon::용이 물속에서 잠듦": "sleeping asleep slept dormant",
  "dragon::용이 문 앞을 지키고 있음": "guarding guarded blocking barring",
  "dragon::용이 죽음": "dead died dying corpse",
  "dragon::용을 타고 산에 오름": "mountain mountains peak hill",
  "dragon::용이 우물 속으로 들어감": "well",
  "dragon::용이 하늘로 날아오름": "flew flying soared ascended ascending rose",
  "dragon::용을 타고 저자에 들어감": "market marketplace bazaar town square",
  "dragon::용이 문 안으로 들어옴": "doorway entrance threshold inside",
  "dragon::용이 부뚜막에 들어옴": "stove kitchen hearth furnace",
  "dragon::뱀이 용으로 변함": "snake serpent turned became transformed",
  "dragon::부인이 용을 봄": "wife woman pregnant lady",
  "dragon::용이 사람을 죽임": "killed killing devoured attacked mauled",
  "dragon::깃발에 용이 있음": "flag banner emblem painted embroidered",
  "feces::똥이 몸을 더럽힘": "smeared body clothes",
  "feces::대변이 땅에 가득함": "ground floor everywhere scattered filled",
  "feces::똥을 지고 집으로 돌아옴": "carrying carried hauling brought home",
  "feces::대변을 잃어버림": "lost losing disappeared missing",
  "feces::똥오줌 속에 있음": "urine pee sewage immersed",
  "feces::뒷간에 똥이 넘침": "outhouse latrine toilet overflowing overflowed",
  "feces::똥 가운데 앉음": "sitting sat squatting middle",
  "feces::똥과 흙이 무더기로 쌓임": "dirt soil pile heap piled",
  "deity::신이 성을 냄": "angry anger furious wrath enraged",
  "deity::신과 부처를 그림": "painting painted drew drawing portrait",
  "deity::신을 모신 사당에 들어가니 신이 움직임": "shrine sanctuary moved moving stirred",
  "deity::신과 귀신에게 맞음": "ghost ghosts beaten struck hit",
  "deity::마루 위에 신과 부처가 있음": "floor porch veranda wooden",
  "deity::신과 부처가 형체를 이루지 못함": "shapeless formless blurred distorted crumbling",
  "deity::신을 맞이하고 마을 제사를 지냄": "ritual rite village festival offering",
  "deity::신과 부처를 바라봄": "looked looking gazed staring beheld",
  "married-couple::부부가 잔치를 벌임": "feast banquet celebration party",
  "married-couple::부부가 서로 꾸짖고 다툼": "scolding quarrel argued arguing bickering",
  "married-couple::부부가 비녀를 나누어 가짐": "ornament split shared divided",
  "married-couple::부부가 서로 때리며 싸움": "hitting beat beating struck punched",
  "married-couple::아내가 남편과 함께 물에 들어감": "water river lake wading",
  "married-couple::부부가 서로 머리를 빗어 줌": "comb combing brushed strands",
  "married-couple::부부가 서로 절을 함": "bow bowed bowing greeting",
  "rice::새 옷에 쌀을 모아 담음": "clothes pocket gathered collected wrapped",
  "rice::멥쌀을 찧어 흰쌀로 만듦": "pounded milled polished husked",
  "rice::쌀과 곡식이 수북이 쌓임": "piled heaped mound abundant plentiful",
  "rice::쌀과 곡식이 흩어짐": "scattered spilled strewn dropped",
  "rice::쌀과 보리가 나란히 놓임": "barley beside laid arranged",
  "rice::쌀과 보리 위에 앉거나 누움": "sat sitting lay lying reclined",
  "tiger::사나운 호랑이가 크게 울부짖음": "roaring roared growling fierce howling",
  "tiger::호랑이를 타고 감": "riding rode mounted back",
  "tiger::호랑이가 집 안으로 들어옴": "entered house came inside home",
  "tiger::호랑이가 움직이지 않고 있음": "still motionless crouching lying quietly",
  "tiger::호랑이를 잡음": "caught captured killed subdued seized",
  "bed::침상 위에 개미가 있음": "ant ants insects crawling",
  "bed::침상 다리를 새로 갈아 끼움": "leg legs replaced repaired",
  "bed::침상에 올라가 누움": "climbing onto lay lying rested",
  "bed::침상에 피가 있음": "blood bloody bloodstain stained",
  "official-robe::남에게 관복을 줌": "gave giving handed offered",
  "official-robe::남이 관복을 줌": "received receiving got obtained",
  "official-robe::여자가 관복을 갖춰 입음": "woman wife lady wearing dressed",
  "official-robe::관복을 새로 물들임": "dyed dyeing colored recolored",
  "words-spoken-by-others::남이 아주 좋다고 말함": "great wonderful praised congratulated",
  "words-spoken-by-others::남이 나더러 죽었다고 말함": "dead died dying",
  "words-spoken-by-others::남이 함께 가자고 말함": "together going along accompany",
  "words-spoken-by-others::남이 너는 필요 없다고 말함": "useless unnecessary worthless rejected",
  "face-powder::분을 얻음": "got obtained received found",
  "face-powder::분을 봄": "saw seeing looked noticed",
  "face-powder::분을 얻어 아내에게 줌": "wife gave giving handed",
  "mud::진흙 속에 빠져 있음": "stuck sinking trapped mired struggling",
  "mud::진흙이 옷을 더럽힘": "clothes clothing soiled dirtied stained",
  "mud::진흙이 적삼을 더럽힘": "shirt jacket sleeve blouse",
  "song::노래하는 것을 봄": "watched saw watching someone else",
  "song::마루 위에서 노래하고 풍악을 울림": "floor porch music instruments festive",
  "song::병자가 노래함": "sick patient ill invalid",
  "bee::벌과 나비가 어우러져 놂": "butterfly butterflies fluttering playing",
  "bee::벌이 사람의 다리를 쏨": "stung sting stinging leg",
  "being-beaten-2::관가에서 매를 맞음": "court magistrate office authorities caning",
  "being-beaten-2::고문과 매질을 당함": "torture tortured whipping interrogation flogging",
  "feast::잔치를 열어 손님을 모음": "guests invited gathered threw hosting",
  "feast::귀인이 베푼 잔치를 받음": "noble dignitary important person honored treated",
  "fishing::물속에서 낚시를 함": "water river sea lake stream",
  "fishing::숲속에서 고기잡이를 함": "forest woods mountain trees grove",
  "melon::문드러진 오이를 먹음": "rotten spoiled mushy decayed",
  "melon::오이씨를 먹음": "seed seeds pips",
  "millet::좁쌀을 먹음": "ate eating eaten swallowed",
  "millet::좁쌀을 봄": "saw seeing looked noticed",
  "rouge::연지를 얻음": "got obtained received found",
  "rouge::연지를 봄": "saw seeing looked noticed",
  "seal::문서에 도장을 찍음": "document paper stamped contract signing",
  "seal::도장을 몸에 지님": "carried carrying kept pocket possession",
  "sword::깃발과 칼이 산속으로 이끌어 들임": "banner flag mountain",
  "sword::칼을 뽑아 들고 길을 나섬": "journey traveled departed setting",
  "sword::남에게서 칼을 얻음": "received obtained acquired",
  "sword::남이 칼 세 자루를 줌": "three swords",
  "sword::남과 더불어 칼로 벰": "together alongside jointly",
  "sword::칼에 다쳐 피가 남": "blood bleeding bled",
  "sword::부러진 칼로 남을 찌름": "broken snapped blunt",
  "sword::칼과 도끼에 스스로 다침": "axe accidentally",
  "sword::남에게서 칼과 도끼를 얻음": "hatchet",
  "sword::칼이 물속에 빠짐": "water river sank drowned",
  "sword::칼을 잃어버림": "lost missing losing",
  "sword::칼을 차고 길을 감": "walking road wearing belt",
  "sword::칼을 갈아 날이 날카로워짐": "sharpen sharpened sharpening whetstone",
  "sword::남에게 칼을 줌": "gave giving handed",
  "sword::칼이 잠자리 머리맡에 있음": "bedside pillow sleeping",
  "sword::여자가 칼을 참": "waist carrying wore",
  "sword::여자가 칼을 뽑음": "woman drew unsheathed",
  "sword::갑옷을 입고 칼을 짚음": "armor armour helmet",
  "sword::칼을 들고 스스로를 찌름": "suicide stabbing himself",
  "sword::칼에 찔림": "stabbed pierced",
  "sword::칼을 들고 서로 싸움": "fight fought duel battle",
  "sword::칼에 스스로 다침": "cut wounded scratched",
  "sword::칼로 남을 벰": "slashed beheaded chopped",
  "fish::물고기가 물 위로 날아오름": "flying flew air",
  "fish::우물 안에 물고기가 있음": "well",
  "fish::그물을 쳐서 물고기를 잡음": "net nets fishing",
  "fish::남이 물고기를 잡아 먹음": "eating ate cooked",
  "fish::물고기를 빼앗아 먹음": "snatched stole grabbed",
  "fish::물고기 떼가 물에서 헤엄침": "swimming school shoal many",
  "fish::큰 물고기가 뛰어오름": "big large jumped leaping",
  "fish::작은 물고기가 새끼를 낳음": "small little spawn babies",
  "fish::마른 물고기가 물에 들어감": "dried dry",
  "fish::몸이 물고기 위에 앉음": "riding sat rode",
  "grave::무덤이 높이 솟아 있음": "tall high rising mound",
  "grave::새 무덤과 관을 봄": "coffin casket corpse",
  "grave::무덤 위에 구름 기운이 서림": "cloud mist vapor haze",
  "grave::무덤의 문이 열림": "door opened opening entrance",
  "grave::무덤 위가 밝음": "bright shining light glowing",
  "grave::무덤 위가 어두움": "dark darkness gloomy shadow",
  "grave::무덤에 나무가 자람": "tree growing grew",
  "grave::무덤의 나무가 꺾임": "broken snapped fell",
  "grave::무덤 위에 꽃이 핌": "flower flowers bloom blossom",
  "star::하늘의 별이 밝게 빛남": "bright shining twinkling",
  "star::별에 절하고 향을 사름": "bowed incense prayed praying",
  "star::별이 품 안으로 들어옴": "bosom chest embrace arms",
  "star::별이 떨어짐": "fell falling fallen",
  "star::별이 줄지어 늘어섬": "row lined rows aligned",
  "star::별을 손에 쥠": "held grasped caught holding",
  "star::흐르는 별이 떨어지지 않음": "streaming flowing hovering",
  "star::별을 손으로 어루만짐": "touched stroking caressed",
  "field::밭에 풀이 자람": "grass weeds overgrown",
  "field::밭을 넓게 갈아 씨를 심음": "plowed tilled planted",
  "field::밭에 씨 뿌리는 사람을 봄": "sowing scattering watched",
  "field::남을 시켜 밭에 씨를 심게 함": "ordered servant hired instead",
  "field::남의 밭을 사들임": "bought buying purchase",
  "field::밭이 무너져 못 쓰게 됨": "collapsed ruined barren useless",
  "buddhist-temple::웃어른께 몸소 절함": "elder elders senior",
  "buddhist-temple::남에게 머리를 조아려 절함": "kowtow bowed head",
  "buddhist-temple::절 안에 들어감": "entered entering inside",
  "buddhist-temple::절에 경전이 놓여 있음": "scripture sutra books",
  "buddhist-temple::비구니 절로 옮겨 감": "nun nunnery convent moved",
  "king::임금을 의장 앞에서 마주함": "faced audience ceremonial",
  "king::임금의 행렬을 봄": "procession parade passing watched",
  "king::임금이 불러들임": "summoned called calling",
  "king::임금이 자리를 내려 줌": "granted position office bestowed",
  "king::임금·제후와 나란히 앉음": "beside sitting lords together",
  "grain::오곡이 무성하게 자람": "lush growing abundant flourishing",
  "grain::곡식 이삭이 고르게 팸": "ears ripening even heads",
  "grain::손에 곡식을 쥠": "hand held handful grasped",
  "grain::벼와 곡식을 얻음": "rice paddy received obtained",
  "immortal::신선을 만나 이야기함": "talked conversation spoke",
  "immortal::노군과 진인을 봄": "Laozi Laojun perfected",
  "immortal::신선과 성인이 집에 옴": "house home visited came",
  "immortal::사원에서 신선을 만남": "temple monastery shrine",
  "bucket::물통에 물이 가득 담김": "full filled brimming",
  "bucket::물통이 비어 물이 없음": "empty dry nothing",
  "bucket::남이 큰 물통을 보내옴": "sent brought large",
  "ceremonial-canopy::깃발과 일산을 만듦": "banner flag making made",
  "ceremonial-canopy::깃털 일산이 몸을 덮음": "feather feathered plume",
  "ceremonial-canopy::흰 일산이 몸을 덮음": "white pale",
  "main-hall::높은 대청에 오름": "high climbed ascended steps",
  "main-hall::대청 위에 관이 놓여 있음": "coffin casket corpse placed",
  "main-hall::안채 대청이 무너져 내림": "collapsed crumbled inner",
  "noble-person::귀인을 만나러 갔으나 만나지 못함": "missed absent failed",
  "noble-person::귀인을 봄": "saw seeing appeared",
  "noble-person::귀인이 말을 달림": "horse riding galloping",
  "writing-brush::손으로 붓과 벼루를 만짐": "inkstone ink touching touched",
  "writing-brush::남이 내 붓을 가져감": "stole taken snatched",
  "writing-brush::남이 붓을 보내 줌": "sent gave received gift",
  "bracelet::팔찌가 비녀와 서로 부딪힘": "hairpin clashing clinking sound",
  "bracelet::은팔찌를 봄": "silver",
  "deer::사슴이 집 안에 있음": "house home inside room",
  "deer::사슴을 잡음": "caught hunted captured hunting",
  "ghost::신과 귀신에게 맞음": "struck beaten attacked",
  "ghost::귀신과 싸움": "fought fighting struggle wrestled",
  "hemp::삼이 몸에 우거짐": "body wrapped around covering",
  "hemp::삼이 숲처럼 우거져 자람": "forest thick dense grove",
  "net::몸이 그물에 걸림": "caught trapped tangled snared",
  "net::그물이 몸을 덮어씌움": "covered thrown draped",
  "soil::몸이 흙 속으로 들어감": "buried sank inside",
  "soil::스스로 흙을 파 가짐": "dug digging took myself",
  "wife::아내가 비단옷을 입음": "silk clothes dressed wearing",
  "wife::아내가 아이를 뱀": "pregnant pregnancy conceived child",
  "fire::불 위에 차려 놓은 것을 봄": "food meal offering cooking",
  "fire::하늘의 불이 문을 태움": "sky gate heaven",
  "fire::물 위에서 불이 나옴": "surface pond sea lake",
  "fire::불이 해와 달을 태움": "sun moon",
  "fire::불이 강물을 태움": "river stream",
  "fire::불이 산과 들을 태움": "mountain field forest",
  "fire::불이 제 집을 태움": "house home",
  "fire::불꽃이 활활 타오름": "flames blazing roaring crackling",
  "fire::불이 땅에서 솟아남": "ground erupting sprang",
  "fire::불을 들고 길을 감": "carrying walking road torch",
  "fire::큰불이 하늘을 태움": "huge enormous entire vast",
  "fire::몸이 불 속에 있음": "inside engulfed surrounded body trapped",
  "fire::불을 잡고 길을 감": "holding gripping gripped clutching",
  "fire::불을 잡고 우물을 태움": "well",
  "fire::집 안에 불빛이 있음": "glow lamp indoors room",
  "fire::부엌에서 불이 남": "kitchen stove hearth",
  "fire::벼슬을 기다리며 불을 켬": "candle lighting appointment office post",
  "fire::사람을 태워 고약한 냄새가 남": "person stench smell flesh corpse",
  "fire::불을 손에 들고 배에 오름": "boat ship boarding",
  "water::물을 마심": "drinking drank sip swallow",
  "water::우물을 파서 물을 봄": "well digging dug bucket",
  "water::물 위를 걸어감": "walking walked crossing",
  "water::물 위에 서 있음": "standing stood floating",
  "water::물이 넘실넘실 흐름": "flowing rushing swirling current",
  "water::물 위에서 불이 나옴": "fire flame burning",
  "water::스스로 물속에 있음": "underwater submerged immersed deliberately",
  "water::물에 빠져 나오지 못함": "drowning struggling trapped escape",
  "water::쉬지 않고 물을 마심": "endlessly ceaselessly thirst gulping",
  "water::흐르는 물이 몸을 감돎": "wrapping surrounding coiling encircling",
  "water::큰물이 맑게 갬": "clear cleared flood calm",
  "water::남의 집에 물이 있음": "neighbor another someone",
  "water::배 안에 물이 고여 있음": "boat ship pooled bilge",
  "mountain::산이 해와 달을 물고 있음": "sun moon holding",
  "mountain::불이 산과 들을 태움": "fire burning flames",
  "mountain::산에 올랐다가 땅에 떨어짐": "fell falling plunged dropped",
  "mountain::산에 오르며 두려워함": "afraid fear scared trembling",
  "mountain::오르던 산이 무너져 내림": "collapsed crumbling landslide caved",
  "mountain::높은 산을 유람하며 구경함": "touring sightseeing scenery view",
  "mountain::높은 산에 자리 잡고 삶": "living settled dwelling home",
  "mountain::산길을 가다 재물을 얻음": "treasure money wealth found",
  "mountain::물건을 안고 산에 오름": "carrying object bundle load",
  "mountain::산속에서 농사를 지음": "farming planting crops field",
  "prison::감옥이 무너짐": "collapsed crumbling ruined",
  "prison::옥에 갇혀 앉아 있음": "sitting locked confined cell",
  "prison::옥에 들어가 재앙을 당함": "disaster calamity misfortune",
  "prison::옥중에서 죽는 사람을 봄": "dying dead corpse death",
  "prison::남을 옥에 들여보냄": "sending another someone reported",
  "prison::감옥 안으로 들어감": "entering walked inside",
  "prison::도적이 스스로 옥에 들어감": "thief robber voluntarily surrendered",
  "prison::감옥이 더럽고 냄새남": "filthy dirty stench smell",
  "kitchen-stove::부뚜막 아래로 물이 흐름": "water flowing underneath wet",
  "kitchen-stove::부뚜막 아래에 불을 땜": "lighting firewood kindling fire",
  "kitchen-stove::부뚜막과 솥이 깨짐": "cauldron pot cracked broken",
  "kitchen-stove::부뚜막 아래에 입김을 불어 넣음": "breath blowing blew",
  "kitchen-stove::부뚜막 아래에서 그릇이 울림": "bowl dish ringing sound",
  "kitchen-stove::집에 부뚜막이 둘 있음": "two second another",
  "kitchen-stove::부엌과 부뚜막을 고쳐 지음": "repairing rebuilding renovating",
  "woman::여자와 함께 길을 감": "together walking road accompanying",
  "woman::여자를 품에 안음": "embraced hugging arms held",
  "woman::여자와 몸을 섞음": "sex intercourse slept intimate",
  "woman::여자와 나란히 앉음": "sitting beside seated side",
  "woman::여자의 음부를 봄": "genitals private parts",
  "woman::여자가 알몸으로 있음": "naked nude bare undressed",
  "mouse::쥐가 참새와 싸움": "sparrow bird fighting fought",
  "mouse::쥐가 고양이에게 잡힘": "cat caught seized",
  "mouse::흰 쥐가 길을 인도함": "white leading guided showed",
  "mouse::쥐가 사람의 옷을 물어뜯음": "clothes gnawing chewed bit",
  "mouse::쥐가 크게 내달림": "running dashing scurrying fast",
  "cauldron::큰 솥을 봄": "huge large giant enormous",
  "cauldron::솥이 넘치도록 가득 참": "overflowing full brimming filled",
  "cauldron::무쇠솥이 깨짐": "iron cracked broke shattered",
  "cauldron::부뚜막과 솥이 깨짐": "stove hearth kitchen",
  "jade::금은과 주옥을 봄": "gold silver pearl",
  "jade::옥이 산처럼 쌓임": "piled heap stacked mound",
  "jade::주옥이 품에 가득함": "bosom chest full",
  "jade::옥 그릇과 기물을 얻음": "vessel bowl utensil received",
  "being-beaten::남에게 맞음": "someone stranger person",
  "being-beaten::남에게 발로 차임": "kicked kicking foot",
  "being-beaten::아내에게 맞음": "wife spouse",
  "crossbow::남이 활과 쇠뇌를 보내 줌": "sent gave received gift",
  "crossbow::쇠뇌에 시위를 걸기 어려움": "string bowstring difficult draw",
  "crossbow::활과 쇠뇌가 서로 다툼": "fighting clashing quarrel",
  "leopard::표범을 봄": "saw seeing watching spotted",
  "leopard::표범 같은 짐승을 봄": "beast animal resembling like",
  "leopard::표범을 잡음": "caught captured killed seized",
  "official::관리를 마주 대함": "facing meeting encountered",
  "official::관리가 관청으로 이끌어 감": "office court led taken",
  "official::관리에게 이름이 적혀 걸림": "name written listed recorded",
  "wolf::이리가 움직이지 않고 있음": "motionless still frozen unmoving",
  "wolf::이리를 봄": "saw appeared spotted",
  "wolf::이리가 다리를 물어뜯음": "leg bit bite gnawed",
  "brazier::옷을 말리는 화로 바구니를 봄": "clothes drying basket",
  "brazier::여러 사람이 화로를 둘러쌈": "people gathered around surrounding",
  "comb::남이 빗을 줌": "gave handed received gift",
  "comb::상아나 나무로 만든 빗을 봄": "ivory wooden wood carved",
  "gold-and-silver-treasure::금은보화를 봄": "riches heap wealth",
  "gold-and-silver-treasure::금은과 주옥을 봄": "pearl jade gems",
  "head::남이 자기 머리를 내리침": "struck hitting blow beaten",
  "head::머리가 잘린 채로 걸어감": "severed headless walking beheaded",
  "pan::구리 냄비를 봄": "copper bronze brass",
  "pan::냄비가 깨짐": "broken cracked shattered",
  "quarrel::남과 서로 욕하며 다툼": "cursing shouting arguing insulting",
  "quarrel::욕을 먹고도 모르는 척함": "ignored pretended endured silent",
  "soldier-setting-out::출정하는 사람이 막 길을 나섬": "leaving departing farewell",
  "soldier-setting-out::출정했던 사람이 돌아옴": "returned returning back home",
  "white-clothing::흰 옷을 입음": "wearing wore dressed",
  "white-clothing::여러 사람이 흰 옷을 입음": "many people everyone crowd",
  "door::문이 높고 큼": "towering large huge grand",
  "door::문을 새로 냄": "installed added cut opening",
  "door::문이 홀연히 열림": "suddenly abruptly unexpectedly",
  "door::문이 활짝 열림": "wide flung fully",
  "door::문을 새것으로 고침": "replaced renewed brandnew",
  "door::문이 저절로 열림": "itself accord automatically",
  "door::문이 갈라져 열림": "split cracked apart gap",
  "door::문이 부서짐": "broken shattered smashed destroyed",
  "door::문이 닫혀 막힘": "closed shut blocked locked",
  "door::문짝이 저절로 부러짐": "snapped panel gave way",
  "door::문 안에 사람이 없음": "empty nobody deserted noone",
  "door::문을 고치거나 옮김": "moved relocated repaired fixing",
  "door::돌로 문을 만듦": "stone rock",
  "door::문 앞에 풀이 자람": "grass weeds growing",
  "door::문 앞에 구덩이와 도랑이 있음": "pit ditch hole trench",
  "door::하늘의 불이 문을 태움": "fire burning burned flames",
  "door::집에 작은 문을 냄": "small little narrow side",
  "tree::마른 나무에 다시 싹이 틈": "sprout budding shoot revived",
  "tree::나무가 말라 죽음": "withered dried dead died",
  "tree::나무가 시들어 잎이 짐": "wilting leaves shedding falling",
  "tree::숲속에 나무가 새로 자람": "forest woods",
  "tree::나무를 심음": "planting planted sapling",
  "tree::큰 나무에 오름": "ascending ascend scaled scaling",
  "tree::오른 나무가 갑자기 부러짐": "climbed plunged tumbled accident",
  "tree::마른 나무에 꽃이 핌": "blossom flowers bloomed blooming",
  "tree::큰 나무가 집 위로 넘어짐": "roof onto crushed toppled",
  "tree::나무 아래에 서 있음": "under beneath shade standing",
  "tree::집 마루 위에 나무가 자람": "floor hall indoors",
  "tree::큰 나무가 갑자기 부러짐": "snapped suddenly broken",
  "tree::나무를 메고 집으로 옴": "carrying carried shoulder home",
  "tree::큰 나무를 베어 넘김": "cutting chopped axe felled",
  "tree::풀과 나무가 우거짐": "lush dense overgrown thick",
  "cloud::구름이 걷힘": "clearing cleared parted lifted",
  "cloud::구름이 갑자기 해를 가림": "sun sunlight hid",
  "cloud::구름이 사방에서 피어오름": "rising everywhere billowing gathering",
  "cloud::오색 구름을 봄": "colorful rainbow",
  "cloud::구름이 붉거나 흼": "reddish white crimson",
  "cloud::구름이 푸르거나 검음": "blue green bluish",
  "cloud::뜬구름을 봄": "floating drifting adrift",
  "cloud::구름과 안개가 앞을 가림": "fog mist haze",
  "cloud::검은 구름이 땅까지 내려옴": "black dark descending ground",
  "hair::부인이 머리를 풀어 헤침": "wife woman lady",
  "hair::머리가 하얗게 셈": "gray grey graying turning",
  "hair::머리가 벗겨지고 머리털이 빠짐": "bald balding scalp receding",
  "hair::머리털이 희어져 빠짐": "whitened losing falling",
  "hair::빠졌던 머리털이 다시 남": "regrew back again growing",
  "hair::맨머리로 머리털을 풀어 헤침": "bare disheveled unbound loose",
  "hair::머리털을 풀어 얼굴을 덮음": "face covering covered veiled",
  "hair::머리를 깎고 머리털을 자름": "cut shaved shaving trimmed",
  "liquor::남이 권하는 술을 마심": "offered pouring urged poured",
  "liquor::남과 함께 술을 마심": "together friends company",
  "liquor::술을 마심": "alone myself",
  "liquor::술에 취하도록 마심": "drunk drunken intoxicated wasted",
  "liquor::귀인과 마주 앉아 술을 마심": "noble dignitary facing sitting",
  "liquor::높은 누각에서 술을 마심": "pavilion tower upstairs",
  "liquor::배 위에서 술을 마심": "boat ship aboard deck",
  "stone::강물 속의 모래와 돌": "river sand stream water",
  "stone::돌 위에 누움": "lying lay rested",
  "stone::돌을 옮겨 집에 들임": "carried brought home moved",
  "stone::돌 위에서 이익과 녹봉을 얻음": "profit salary gain reward",
  "stone::돌을 품에 안음": "embraced bosom hugged holding",
  "stone::손으로 작은 돌을 만지작거림": "fiddling handling fingers pebble",
  "snow::눈이 내림": "heavily thickly",
  "snow::눈이 때맞추어 내림": "timely season proper",
  "snow::눈이 몸 위에 내려 쌓임": "piled shoulders accumulated covered",
  "snow::눈이 몸에 묻지 않음": "stick touch melted brushed",
  "snow::눈이 집 뜰에 내림": "yard garden courtyard",
  "bow::활과 화살을 지님": "arrows quiver carrying holding",
  "bow::활을 당기다 시위가 끊어짐": "string snapped drawing broke",
  "bow::남이 활과 쇠뇌를 보내 줌": "sent gave gift received",
  "bow::활과 쇠뇌가 서로 다툼": "fighting contending quarrel rivalry",
  "money::남에게 돈과 물건을 돌려줌": "returned repaid returning",
  "money::돈과 물건을 주움": "picked found ground",
  "money::봄과 여름에 돈을 봄": "spring summer",
  "money::가을과 겨울에 돈을 봄": "autumn winter fall",
  "bathing::목욕을 함": "washed clean refreshed",
  "bathing::남녀가 목욕하고 잠자리에 오름": "man woman bed sleeping together",
  "bathing::티끌과 흙으로 목욕함": "dirt mud dust muddy",
  "curtain::장막을 열어젖힘": "opened drew lifted pulled",
  "curtain::장막이 무너지고 헐어짐": "collapsed crumbled worn sagging",
  "curtain::장막을 훼손함": "damaged tore ripped destroyed",
  "kitchen::부엌과 부뚜막을 고쳐 지음": "repaired rebuilt renovated fixing",
  "kitchen::관청 부엌 안에 있음": "office government official",
  "kitchen::부엌에서 불이 남": "fire burning flames caught",
  "pavilion::누각에 오름": "climbed climbing ascended",
  "pavilion::높은 누각에서 술을 마심": "drinking wine liquor",
  "pavilion::집에 높은 누각을 세움": "built building erected",
  "wall::담을 넘어 집으로 들어감": "over entered climbing inside",
  "wall::아내와 아들이 담 아래 있음": "wife son family beneath",
  "wall::담 위에서 흙을 팜": "digging dug soil earth",
  "buddhist-nun::스님과 비구니가 경을 봄": "monk sutra scripture reading",
  "buddhist-nun::비구니와 정을 통함": "affair intimate relations love",
  "clam::새우와 조개가 울며 달아남": "shrimp fleeing running crying",
  "clam::조개를 봄": "saw seeing spotted",
  "gold-and-silver-vessel::금은으로 만든 잔과 그릇을 봄": "cup cups goblet saw",
  "gold-and-silver-vessel::금은으로 솥과 그릇을 만듦": "cauldron pot making made",
  "paper::오색 종이를 봄": "colored colorful saw",
  "paper::오색 종이를 삼킴": "swallowed swallowing ate",
  "pork::돼지고기를 먹음": "eating ate eat",
  "pork::칼로 돼지고기를 자름": "knife cutting cut sliced",
  "sparrow::참새가 쥐와 싸움": "mouse rat fighting fought",
  "sparrow::참새가 시끄럽게 지저귐": "chirping noisy loudly twittering",
  "thread::실과 명주를 찾음": "silk searching looking found",
  "thread::실을 얻음": "obtained received got",
  "horse::말이 뜰 앞에서 춤추듯 뛰놂": "dancing prancing frolicking courtyard yard",
  "horse::말이 천 리 길을 달림": "thousand miles journey distance",
  "horse::탄 말이 빠르게 내달림": "fast swiftly galloping speeding",
  "horse::탄 말이 굼떠 나아가지 못함": "sluggish slow reluctant refused",
  "horse::말이 오가며 내달림": "roaming wandering forth",
  "horse::말이 돈과 물건을 등에 싣고 감": "carrying load luggage goods cargo",
  "horse::말이 방 안으로 들어옴": "room bedroom indoors",
  "horse::말을 씻겨 풀어 놓아 줌": "washing washed bathing released freed",
  "horse::말 떼가 멀리 달려 나감": "herd stampede away",
  "horse::죄인이 말을 달려 감": "criminal fugitive fleeing convict",
  "horse::말에게 물림": "bit bitten bite",
  "horse::흰 말을 타고 감": "white pale riding",
  "horse::집 안에서 말이 태어남": "born newborn",
  "horse::말을 잡음": "caught catching capture seized",
  "horse::집 안에서 말이 새끼를 낳음": "foal offspring gave",
  "horse::흰 말이 수레를 끎": "cart wagon pulling pulled",
  "horse::말 네 마리가 수레를 끎": "four team chariot",
  "horse::말을 갖추어 채비함": "prepared saddled equipped ready",
  "horse::귀인이 탄 말이 달림": "noble nobleman official dignitary",
  "ox::누런 소가 집으로 옴": "yellow brown",
  "ox::물소를 봄": "saw spotted watching",
  "ox::소가 산비탈을 올라감": "slope hillside uphill",
  "ox::소를 끌고 산에 오름": "leading pulling mountain climb",
  "ox::소뿔에 피가 묻어 있음": "blood bloody stained",
  "ox::소가 사람을 뿔로 받음": "gored butted charged",
  "ox::소가 문 밖으로 나감": "outside gate leaving",
  "ox::물소가 집으로 옴": "buffalo came arrived",
  "ox::소가 송아지를 낳음": "calf birth calved",
  "ox::소를 타고 성 안으로 들어감": "riding rode castle fortress",
  "ox::소를 끌고 집으로 돌아옴": "returned brought home",
  "ox::소를 잡음": "caught captured seized",
  "ox::소를 잡아 고기를 먹음": "meat beef eaten eating",
  "banner::깃발에 용이 그려져 있음": "dragon drawn painted embroidered",
  "banner::깃발과 부절을 품에 안음": "embraced bosom chest hugged",
  "banner::깃발과 칼이 산속으로 이끌어 들임": "sword mountain led into",
  "banner::깃발과 일산을 만듦": "parasol canopy made",
  "banner::깃발을 들고 나가 맞이함": "greet welcome meeting",
  "banner::깃발이 끝내 밖으로 나감": "outside away gone",
  "banner::손에 깃발과 부절을 듦": "hand holding held tally",
  "banner::새 깃발을 만드는 것을 봄": "new making watched",
  "banner::번과 일산을 만듦": "streamer pennon",
  "coffin::대청 위에 관이 놓여 있음": "hall floor placed lying",
  "coffin::새 무덤과 관을 봄": "grave tomb new",
  "coffin::관이 무덤에서 저절로 나옴": "spontaneously itself emerged",
  "coffin::관을 집으로 들임": "house brought carried inside",
  "coffin::시신이 관 밖으로 나옴": "outside slipped corpse",
  "coffin::관을 열고 죽은 사람과 말함": "opened talked spoke dead",
  "coffin::관에 시신을 넣는 것을 봄": "putting sealed encoffin",
  "coffin::물 위에 뜬 관을 봄": "floating water river ocean",
  "straw-mat::돗자리를 집 안으로 들임": "brought inside carried",
  "straw-mat::돗자리를 집 밖으로 내보냄": "outside removed away",
  "straw-mat::돗자리가 해어져 찢어짐": "worn torn tattered frayed",
  "straw-mat::돗자리를 새것으로 바꿔 들임": "new fresh replaced",
  "straw-mat::돗자리를 바꾸어 내보냄": "exchanged swapped",
  "straw-mat::돗자리와 대자리를 봄": "bamboo rush together",
  "straw-mat::돗자리를 훼손함": "damaged ruined broke",
  "straw-mat::돗자리를 펴고 여럿이 함께 앉음": "spread sat sitting",
  "bird::공중에서 새가 욺": "sky air crying chirping sang",
  "bird::나는 새가 품에 들어옴": "bosom chest embrace flew into",
  "bird::나는 새를 붙잡음": "caught grabbed seized",
  "bird::새가 달려오고 뱀이 다가옴": "snake approaching slither",
  "bird::새를 죽임": "killed killing kill",
  "chicken::닭을 씻김": "washing washed bathed",
  "chicken::닭이 욺": "crowing crowed cried",
  "chicken::닭이 알을 품음": "eggs brooding nest hatching",
  "chicken::닭이 나무 위에 있음": "tree branch perched",
  "chicken::닭을 잡음": "caught grabbed seized",
  "axe::칼과 도끼에 스스로 다침": "sword knife blade",
  "axe::남에게서 칼과 도끼를 얻음": "received given gift someone",
  "axe::창과 도끼에 빛이 남": "spear shining glowing gleam",
  "axe::도끼에 스스로 다침": "myself accidentally wounded hurt",
  "grass::문 앞에 풀이 자람": "gate door entrance front",
  "grass::풀과 나무가 우거짐": "trees overgrown dense lush",
  "grass::밭에 풀이 자람": "field farm crops",
  "grass::집 안에 풀이 자람": "house inside home room",
  "shackles-2::칼과 족쇄가 몸에 채워짐": "cangue locked bound body",
  "shackles-2::족쇄가 부러져 망가짐": "broken snapped shattered",
  "shackles-2::족쇄가 집 안으로 들어옴": "house entered inside home",
  "shackles-2::족쇄를 두려워함": "afraid feared frightened dread",
  "death::남이 죽는 것을 봄": "someone else friend stranger",
  "death::자기가 죽음": "myself own oneself",
  "death::자식이 죽음": "child son daughter",
  "killing-someone::남을 죽임": "else stranger unknown",
  "killing-someone::사람을 죽여 피가 옷을 적심": "blood clothes stained soaked",
  "killing-someone::사람을 죽이는 것을 봄": "watched witnessed saw",
  "pine-tree::소나무가 배 위에 자람": "boat ship deck",
  "pine-tree::집 안에 소나무가 자람": "house indoors inside",
  "pine-tree::지붕 위에 소나무와 잣나무가 자람": "roof cypress rooftop",
  "vessel::그릇에 보석을 박아 꾸밈": "jewel gems inlaid decorated ornamented",
  "vessel::그릇이 우물에 떨어짐": "well fell dropped",
  "vessel::부뚜막 아래에서 그릇이 울림": "stove hearth rang sound noise",
  "candle::촛불을 봄": "single alone lit",
  "candle::등불과 촛불이 밝게 빛남": "lamp lantern bright shining",
  "chisel::끌을 봄": "lying saw found",
  "chisel::남이 끌을 건네줌": "gave handed received someone",
  "goose::거위와 오리가 함께 헤엄침": "duck ducks swimming water together",
  "goose::거위를 잡음": "caught grabbed seized",
  "hammer::망치와 송곳을 봄": "awl gimlet together",
  "hammer::망치를 들려 하는데 잡아 주는 사람이 있음": "lifting helped someone assist",
  "peacock::공작을 봄": "saw standing spotted",
  "peacock::공작이 날며 춤춤": "flying dancing wings spread",
  "phoenix::봉황을 봄": "saw appeared spotted",
  "phoenix::봉황이 손바닥에 내려앉음": "palm hand landed perched alighted",
  "spear::창을 봄": "saw standing spotted",
  "spear::창과 도끼에 빛이 남": "axe shining gleaming light",
  "teeth::이가 저절로 빠짐": "fell falling loose",
  "teeth::빠진 이가 다시 남": "grew regrew again new",
  "boat::배를 먹음": "ate eating pear fruit sweet",
  "boat::배가 지붕 위를 지나감": "roof rooftop tiles eaves",
  "boat::배가 하늘을 날아감": "sky airborne flew air ascended",
  "boat::배가 얕은 물에서 언덕에 걸림": "shallow shore aground stuck stranded sandbank",
  "boat::배를 타고 강을 건넘": "river crossing crossed cross ferry",
  "boat::배 안에 물이 고여 있음": "leaking leak flooded pooled bilge swamped",
  "boat::배를 타고 해와 달을 봄": "sun moon sunlight moonlight watched gazing",
  "boat::배를 타고 해와 달을 지나감": "passed passing sailed beyond glided",
  "boat::배를 타고 술을 마심": "drinking drank liquor wine alcohol",
  "boat::남과 한 배를 탐": "together others companion shared aboard",
  "boat::배가 돛에 바람을 받아 나아감": "sails wind breeze forward",
  "boat::배를 타고 키를 봄": "rudder helm steering tiller",
  "boat::배를 타고 다리 밑을 지남": "bridge underneath beneath arch",
  "boat::앓는 사람이 배를 탐": "sick illness patient ailing",
  "boat::아버지를 도와 배를 탐": "father dad helping helped",
  "boat::몸이 배 안에 누움": "lying lay asleep sleeping resting",
  "boat::불을 들고 배에 오름": "fire torch lamp lantern carrying",
  "boat::집 안에서 배를 탐": "house home indoors room courtyard",
  "boat::배를 타고 꽃을 봄": "flower flowers blossoms blooming",
  "boat::배가 부서져 깨짐": "broke broken wrecked sank sinking capsized",
  "bridge::다리를 고쳐 손봄": "repair repaired repairing fixing mending",
  "bridge::다리를 건너는 것을 봄": "crossing crossed across walking over",
  "bridge::다리 위에 앉아 있음": "sitting sat perched",
  "bridge::다리가 무너진 것을 봄": "collapsed collapsing crumbled caved",
  "bridge::손을 잡고 함께 다리에 오름": "holding hands together climbed",
  "bridge::다리 위에서 소리쳐 부름": "shouting shouted calling yelled",
  "bridge::다리를 새로 놓음": "new build built building constructed",
  "bridge::다리가 끊어짐": "snapped severed cut broke apart",
  "bridge::다리 기둥이 부러짐": "pillar pier post column support",
  "bridge::다리와 길 위로 수레가 지나감": "cart wagon carriage road passing",
  "bridge::배로 다리 밑을 지나감": "boat sailing underneath beneath",
  "mirror::거울에 비친 모습이 밝음": "bright brightly clear vivid glowing",
  "mirror::거울에 비친 모습이 어두움": "dark darkly dim gloomy murky",
  "mirror::깨진 거울로 사람을 비춤": "cracked chipped split fractured",
  "mirror::거울이 밝게 비침": "shining shone gleaming sparkling radiant",
  "mirror::거울이 어둡게 흐림": "cloudy blurry foggy hazy dull tarnished",
  "mirror::거울을 주움": "picked found lying ground",
  "mirror::거울로 자기를 비춰 봄": "myself self own face",
  "mirror::거울로 남을 비춤": "another person else others",
  "mirror::남의 거울을 얻음": "received got given borrowed",
  "mirror::남이 자기 거울을 만지작거림": "touching touched handling fiddling",
  "mirror::거울이 깨짐": "broke breaking shattered smashed pieces",
  "shoes::남이 자기 신을 신음": "someone else another wearing mine",
  "shoes::신을 얻음": "got received obtained new pair",
  "shoes::신을 잃어버림": "lost losing missing gone disappeared",
  "shoes::신을 벗음": "removed barefoot took",
  "shoes::신이 해져 떨어짐": "worn torn tattered hole ragged",
  "shoes::삼으로 삼은 신을 신음": "straw hemp woven sandals",
  "shoes::빌어서 신을 얻음": "borrowed borrowing lent begged",
  "shoes::나막신이 벗겨짐": "clogs slipped came off",
  "hat::관을 쓰고 수레에 오름": "cart carriage wagon riding",
  "hat::스스로 두건과 모자를 씀": "myself headscarf kerchief wearing",
  "hat::관을 쓰고 높은 대에 오름": "high platform terrace climbed tall",
  "hat::귀인이 관을 줌": "noble nobleman gave gift received",
  "hat::관을 새것으로 바꿔 씀": "new replaced changed swapped",
  "hat::관모가 불에 타 없어짐": "burned burnt fire ashes",
  "hat::관모를 잃어버림": "lost missing gone disappeared",
  "belt::남이 허리띠를 보내옴": "sent gave brought someone",
  "belt::관복의 띠를 주움": "picked found official robe",
  "belt::허리띠를 맴": "fastened wore wearing",
  "belt::옷의 띠가 저절로 풀림": "undone loosened untied itself",
  "belt::띠를 졸라맴": "tightened tight cinched pulled",
  "crane::학이 하늘로 올라감": "sky rose ascending soaring upward",
  "crane::학이 욺": "cried crying call calling",
  "crane::학이 품속으로 들어옴": "arms bosom embraced chest",
  "crane::학이 수레를 끎": "cart pulling pulled wagon",
  "crane::학을 놓아 줌": "released freed let loose",
  "army::군마가 성으로 들어옴": "warhorses entered fortress walls gate",
  "army::군대 진영 안에 있음": "camp barracks encampment inside",
  "army::장수와 병졸이 뒤따름": "general following followed behind troops",
  "army::군대가 패하는 것을 봄": "defeated defeat losing lost routed",
  "hairpin::금비녀가 흔들려 움직임": "shaking swaying trembling moved",
  "hairpin::비녀와 팔찌가 서로 부딪힘": "bracelet clinked knocked together",
  "hairpin::금비녀가 환하게 빛남": "shining glowed sparkled golden",
  "hairpin::꽃을 새긴 비녀를 봄": "flower carved engraved pattern",
  "rope::밧줄이 몸을 묶음": "tied bound wrapped around restrained",
  "rope::밧줄을 봄": "lying coiled hanging",
  "rope::밧줄이 끊어짐": "snapped broke breaking severed",
  "dog::사나운 개를 봄": "fierce vicious ferocious growling angry",
  "dog::개가 사람을 보고 짖음": "stranger passerby unfamiliar someone",
  "dog::개가 주인을 보고 짖음": "owner master household",
  "insect::병든 몸에 벌레가 생김": "sick ill wound sores infested appeared",
  "insect::몸 위로 벌레가 기어감": "crawling crawled creeping over",
  "insect::몸이 벌레 위에 앉음": "sat sitting pressed squashed",
  "scissors::가위를 봄": "lying there noticed spotted",
  "scissors::가위로 물건을 자름": "cut cutting snipped trimmed",
  "scissors::가위의 다리가 부러짐": "broke broken snapped blade",
  "urine::오줌이 몸을 더럽힘": "soiled stained wet dirty splashed",
  "urine::소변을 잃어버림": "lost losing incontinence hold",
  "cart-wheel::수레바퀴가 부서짐": "broke shattered smashed",
  "cart-wheel::수레바퀴가 꺾여 넘어짐": "bent buckled toppled tipped fell",
  "child::어린 아들딸을 품에 안음": "held embraced arms hugging cradled",
  "child::어린아이가 죽음": "died death passed away dying",
  "government-office::관청 안에 앉아 있음": "sitting sat inside seated",
  "government-office::남을 관가로 불러들임": "summoned called brought dragged",
  "greens::온갖 나물을 먹음": "all kinds various assorted many",
  "greens::먹는 나물이 누렇게 뜬 것을 봄": "yellowed wilted withered pale spoiled",
  "persimmon::감과 귤을 먹음": "tangerine tangerines mandarin citrus",
  "persimmon::감과 복숭아를 먹음": "peach peaches",
  "person-reading-a-book::책 읽는 사람을 봄": "scholar student studying aloud",
  "person-reading-a-book::남이 책 읽는 것을 봄": "someone else another",
  "steamed-bun::만두를 먹음": "ate eating delicious full",
  "steamed-bun::만두를 보고도 먹지 못함": "unable hungry watched only stared",
  "swallow::제비가 날아 품에 들어옴": "arms bosom chest into",
  "swallow::제비가 날아옴": "flew flying arrived came"
};
