// 상징 사전의 **상황**을 영어 매칭 키워드로 옮긴 표.
//
// **`scripts/build-dream-contexts.ts`가 만든 파일이다.** 손으로 고쳐도 되지만 규칙이 있다 —
// 이것은 읽기용 문장이 아니라 **매칭 키워드**이고, 기능어(the·is·or)를 넣으면 모든 의미가
// 고르게 점수를 받아 판별이 무작위가 된다.
//
// 이 표가 없으면 영어 글에서 상황 판별이 통째로 죽는다 — 「A snake bit me」가 재물 꿈으로
// 읽힌다(2026-08-07까지 실제로 그랬다). 빠진 자리는 `verify-dream-context-parity`가 센다.

export const CONTEXT_EN: Record<string, string> = {
  "돼지가 집에 들어오거나 품": "pig enter entering hold held",
  "임신 태몽 아기 아이 임산부 출산": "pregnant pregnancy expecting baby infant childbirth",
  "뱀을 잡거나 품": "catch caught hold held holding",
  "뱀에게 물림": "bite bitten bit",
  "뱀이 용으로 변함": "turned into dragon became dragon transformed",
  "뱀의 색이 붉거나 검음": "red black",
  "뱀의 색이 푸르거나 초록": "blue green",

  // 돼지 — 죽임 / 저절로 죽음 (주공해몽, 2026-08-26)
  "돼지를 죽임": "killed killing slaughter slaughtered butchered",
  "돼지가 저절로 죽음": "died dying naturally sick illness",

  // 죽음 — 본인이 죽음 / 타인이 죽음 (주공해몽, 2026-08-26)
  // **"died"를 넣지 않는다** — 두 의미 모두에 해당하는 낱말이라 넣으면 항상 동점이 나고
  // 먼저 검사되는 이쪽이 늘 이긴다(`dream-contexts-ko.ts`와 같은 이유, 실측으로 확인).
  // 주어를 가리키는 낱말만 남긴다.
  "자신이 죽음": "myself personally own",
  "타인이 죽는 것을 봄": "someone else friend family father mother",

  // 죽음 — 3차 확장 (주공해몽, 2026-08-26)
  "타인에게 살해당함": "was murdered was attacked stabbed by",
  "타인을 죽임": "murdered strangled stabbed someone",
  "스스로 목숨을 끊음": "suicide took my own life ended my life",
  "죽은 사람이 서 있음": "standing stood upright",
  "죽은 사람이 되살아남": "revived resurrected alive again",

  "용이 승천": "dragon ascend ascending",
  "용이 죽음": "died dying death",
  "용을 타고 이동함": "rode riding ride",
  "용이 우물에 들어감": "well",
  "호랑이를 타거나 물리침": "tiger ride riding defeat defeated",
  "호랑이에게 쫓김": "tiger chase chased",
  "호랑이가 집에 들어옴": "entered house came into my home",
  "온순한 개": "gentle friendly tame wagging calm approached",
  "개에게 물림": "bit bite bitten attacked growled",
  "고양이가 노려봄": "cat stare staring",
  // 고양이 — 쥐를 잡음 (주공해몽, 2026-08-26)
  "고양이가 쥐를 잡음": "mouse rat caught catching",
  "말을 탐": "horse seek seeking",
  "수탉이 욺": "chicken crowing",
  "닭이 알을 품음": "hatching brooding egg",
  "물고기를 잡음": "fish catch caught",
  "잉어가 뛰어오름": "carp jump jumped",
  "새가 날아옴": "bird fly flying",
  "새가 품에 듦": "held embraced arms",
  "까치가 욺": "magpie crowing",
  "까마귀가 욺": "crow cawing",
  "까마귀가 다른 새와 시끄럽게 다툼": "quarreling noisy fighting",
  "거북이가 나타남": "turtle appear appearing",
  // **"rat"·"mouse"를 뺐다** — term_en이 "rat / mouse"라 ownTerms 정확 일치 검사가 이
  // 낱말들을 못 걸러내(§10 #? "alcohol / wine"과 같은 종류), 아무 쥐 관련 문장에나
  // 공짜 점수를 줘 "흰 쥐가 길을 인도함"과 동점을 냈다(실측으로 확인).
  "쥐가 곡식을 모음": "gather gathered",
  "쥐가 물건을 갉음": "gnaw gnawed",
  "흰 쥐가 길을 인도함": "led guided leading",
  "곰을 봄": "bear see saw",
  "사슴을 봄": "deer see saw",
  "사슴이 집 안에 있음": "inside house home",
  "토끼를 봄": "rabbit see saw",
  "토끼가 하늘로 오름": "rising ascending sky",
  "봉황이 나타남": "phoenix appear appearing",
  "나비가 날아듦": "butterfly fly",
  "벌떼": "bee swarm",
  "벌에 쏘임": "bee sting stung",
  "아침 거미": "spider morning",
  "거미줄에 얽힘": "spider web entangle",
  "개구리가 뜀": "frog jump",
  "벌레가 들끓음": "insect swarm",
  "탁한 물": "muddy water",
  "맑은 물의 큰 홍수": "clear clean huge rose rising",
  "휩쓸림": "swept sweep carried away washed drowning",
  "잔잔한 바다": "sea calm",
  "거친 파도": "sea rough wave",
  "강을 건넘": "river cross",
  "활활 크게 타오름": "fire blaze",
  "작은 불·꺼져감": "fire small extinguish",
  "산 정상에 오름": "peak summit",
  "산에 올랐다가 떨어짐": "mountain fell falling fall",
  "무성한 나무": "tree lush",
  "나무가 말라 죽음": "tree withered dying died dead",
  "활짝 핀 꽃": "bloom blooming blossom full open",
  "시든 꽃": "wilted withered dying dead drooping",
  "남에게 꽃을 나눠 줌": "gave giving handed shared",
  "떠오르는 태양": "sun rise",
  "밝은 보름달": "moon bright",
  "별이 품에 듦": "star hold held",
  "별이 떨어짐": "star fell falling fall",
  "별을 손에 쥠": "star grasped grip clutched hand",
  "선명한 무지개": "rainbow appear appearing",
  "무지개 색이 검음": "rainbow black dark",
  "깨끗한 눈": "clean white fresh piled untouched",
  "눈보라": "blizzard storm trapped freezing howling",
  "강한 바람": "wind blow blowing",
  "바람이 옷깃을 스침": "wind brushed collar clothes",
  "번개가 침": "lightning strike striking",
  "번개가 몸을 비침": "lightning flash lit glow",
  "벼락을 맞음": "struck thunderbolt hit",
  "오색구름": "cloud colorful",
  "먹구름": "cloud dark",
  "구름이 사방에서 일어남": "rising everywhere directions arose",
  "맑은 물이 솟는 우물": "well water rise rising",
  "우물이 마름": "dried dry up",
  "우물에 빠짐": "fell falling fall into",
  "땅이 흔들림": "earthquake shake shaking",
  "땅이 갈라짐": "ground crack cracked split cracking",
  "윗니가 빠짐": "upper top front",
  "피 없이 빠짐": "without blood painless bleeding none",
  // 아랫니 (주공해몽, 2026-08-26)
  "아랫니가 빠짐": "lower bottom back",
  "이가 빠졌다가 다시 남": "grew back regrew growing again new tooth",
  "머리가 빠짐": "hair fall falling",
  "머리를 감음": "washed shampooed",
  "머리를 자름": "hair cut cutting",
  "피를 봄/묻음": "blood see seeing",
  "똥을 밟거나 몸에 묻음": "feces step stepping",
  "대소변을 실수로 지림": "wet accident soiled",
  "시원하게 봄": "urine relieve relieving",
  "손톱이 빠짐": "nail fall falling",
  "사람들 앞에서 벌거벗음": "being naked stand standing",
  "개의치 않음": "being naked not care",
  "임신한 꿈": "pregnancy dream",
  "피나는 상처": "wound bleed bleeding",
  "밝게 보임": "eye bright",
  "높은 곳에서 떨어짐": "falling drop dropping",
  "자유롭게 낢": "freely free soaring high joy",
  "떨어질까 두려움": "afraid fear feared falling scared anxious",
  "무언가에 쫓김": "chase chased",
  // **"chase/chasing"을 넣지 않는다** — 이 상징 자체가 그 낱말로 걸려서 온 것이라 두 의미
  // 모두에 항상 점수를 주고, 먼저 검사되는 이 의미가 동점에서 늘 이겨 "놓침"이 안 뽑힌다
  // (`dream-contexts-ko.ts`와 같은 이유, 실측으로 확인).
  "동물이나 사람을 쫓아감": "caught catching gained closing",
  "쫓다가 놓침": "lost losing missed escape escaped",
  "시험을 못 봄": "test fail failed",
  // **클렌징(2026-08-27) — own-term 필터가 못 거르는 낱말을 뺐다.** term_en이
  // "wedding / marriage"라 "wedding"이 문자 그대로는 안 걸러져 아무 결혼 문장에나
  // 공짜 점수를 줬다("attended a friend's wedding"이 자기 결혼으로 잘못 골라짐,
  // 실측으로 확인) — 6·10차 배치에서 찾은 term_en 슬래시 버그와 같은 종류다.
  "본인의 결혼": "myself personally own",
  "남의 결혼을 봄": "someone else's friend's",
  "자신/타인의 죽음": "death die dying",
  "펑펑 욺": "cry crying",
  "크게 웃음": "laugh laughing",
  "싸워 이김": "fight win won",
  "길을 못 찾음": "get lost lose",
  "깨끗이 씻음": "bathe wash",
  "먼지투성이인 채로 목욕함": "dust dusty dirty grimy",
  "위로 올라감": "climb ascend",
  "아래로 내려감": "descend fall",
  "맛있게 배불리 먹음": "eat eaten",
  "물에 빠져 허우적": "drown struggle",
  "순산": "give birth",
  "땅을 파 무언가 나옴": "dig uncover",
  "소중한 것을 잃음": "lose lose lost",
  "돈이 들어옴": "came received earned gained arrived",
  "돈을 주움": "picked picking street ground floor",
  "돈을 잃어버림": "lost losing money stolen",
  "빌린 돈을 갚음": "repaid repaying paid back returned borrowed",
  "금·보석을 얻음": "gold jewel obtain",
  "반지를 낌": "ring wear",
  "반지를 잃음": "ring lose lost",
  "칼을 쥠": "held holding grip wielded carried",
  "칼에 다침": "cut wounded stabbed bleeding hurt",
  "칼을 잃어버림": "lost losing missing",
  "새 신발": "shoe wear",
  "신발을 잃음": "shoe lose lost",
  "신발이 해짐": "worn out tattered frayed",
  "새 옷을 입음": "clothes wear wore",
  "옷이 갑자기 찢어짐": "torn ripped tore suddenly",
  "거울을 봄": "mirror see saw",
  "거울이 밝음": "bright shining clear polished",
  "거울이 어두움": "dark dim cloudy tarnished",
  "열쇠를 얻음": "key get got",
  "크고 좋은 집": "large big fine spacious grand",
  "허물어지는 집": "collapsing crumbling collapsed ruined cracked",
  "집에 아무도 없음": "empty deserted silent vacant",
  "차를 잘 몲": "car drive drove",
  "사고·브레이크 고장": "car crash break fail",
  "배를 타고 나아감": "boat ship sail sailed",
  "다리를 건넘": "bridge cross crossed",
  "잘 손질된 무덤": "well-maintained tended neat",
  "무덤에 나무가 자람": "tree grew growing",
  "무덤의 나무가 꺾임": "broke snapped broken",
  "관을 봄": "coffin see saw",
  "관에 시신을 넣는 것을 봄": "body corpse placed",
  "쌀·밥이 가득함": "rice full",
  "쌀이 흩어짐": "scattered spilled",
  "책을 얻거나 읽음": "found obtained borrowed",
  "누군가 글을 가르쳐 줌": "taught teaching",
  "편지를 받음": "received got arrived",
  "편지를 써서 보냄": "sent mailed wrote",
  "총을 겨눔/맞음": "gun aim shoot",
  "계단을 오르내림": "stairs climb descend",
  "우산을 씀": "umbrella use used",
  "우산을 남에게 나눠 줌": "gave giving handed shared",
  "멈추거나 잃은 시계": "watch clock stop lose",
  "밝은 표정의 조상": "ancestor deceased bright face",
  "무언가 요구/어두움": "ancestor deceased demand dark",
  "예쁜 아기": "baby pretty",
  "우는 아기": "baby cry crying",
  "유명인과 친해짐": "celebrity befriend befriended",
  "높은 사람을 만남": "president king meet met",
  "성직자의 인도": "guide guided leading",
  "스님이 가르침을 줌": "taught teaching",
  "스님이 경 읽는 모습을 봄": "reading sutra watched",
  "신령이 나타남": "appear appeared",
  "신에게 맞음": "struck hit beaten",
  "귀신과 싸움": "fought fighting ghost",
  "낯선 이와 만남": "meet met",
  "옛 연인이 나옴": "see saw",
  "많은 사람에 둘러싸임": "surround surrounded",
  "학교로 돌아감": "return returned",
  "깨끗한 화장실/시원한 배설": "clean spotless fresh relief tidy",
  "더러운 화장실": "filthy dirty foul stinking clogged",
  "절에서 기도": "pray prayed",
  "북적이는 시장": "visit visited",
  "치료 받음": "receive received",
  "갈림길": "choose chose",
  "물속을 편히 다님": "swim swam",
  "맑고 넓은 하늘": "see saw",
  "흰 옷·흰 동물": "wear wore",
  "선명한 빨강": "see saw",
  "검은색": "see saw",
  "금빛으로 빛남": "shine shone",
  "7이 반복": "repeat repeated",
  "3이 반복": "repeat repeated",
  "코끼리를 봄": "see saw",
  "사자를 봄/제압": "see saw",
  "늑대에 쫓김": "chase chased",
  "독수리가 하늘을 낢": "fly flew",
  "비둘기가 날아옴": "dove fly flying",
  "양떼": "sheep flock",
  "큰 고래를 봄": "whale see saw",
  "상어가 나타남": "shark appear appeared",
  "문어에 감김": "octopus wrap wrapped",
  "물 위의 오리 한 쌍": "duck pair",
  "공작이 날개를 폄": "peacock spread spread wings",
  "부엉이가 응시": "owl stare stared",
  "여우를 만남": "fox meet met",
  "개미가 줄지어 감": "ant march marching",
  "모기에 시달림": "mosquito suffer suffered",
  "게를 잡음": "crab catch caught",
  "땅속 지렁이": "earthworm underground",
  "거대한 공룡": "dinosaur giant",
  "혜성이 지나감": "comet pass passed",
  "화산 폭발": "volcano erupt erupted",
  "동굴 속": "cave inside",
  "외딴 섬": "island remote",
  "미끄러운 얼음": "ice slippery",
  "짙은 안개": "fog thick",
  "휘몰아치는 회오리": "tornado whirl whirlpool",
  "맑은 계곡물": "valley clear water",
  "솟는 샘물": "spring water rise rising",
  "큰 바위": "big large solid",
  "돌 위에 누움": "lay lying lied atop",
  "진주를 얻음": "pearl obtain obtained",
  "발을 다침": "foot hurt hinder progress",
  "계속 늦음": "being late continue late unprepared pressure",
  "어딘가 숨음": "hiding hide somewhere avoid fear",
  "글·서류를 씀": "writing write document achievement",
  "쓰던 필기구를 남에게 줌": "gave giving handed lent",
  "왕관을 씀": "crown wear wearing",
  "지갑을 잃음": "wallet lose lost",
  "안경을 씀": "glasses wear wearing",
  "사진을 찍음": "camera take taking",
  "약을 먹음": "medicine take taking",
  "바늘에 찔림": "needle prick pricked",
  "종소리": "bell ring ringing",
  "아름다운 그림": "painting see saw",
  "편안한 침대": "bed lie lying",
  "쌍둥이를 봄": "twins see saw",
  "군인을 봄": "soldier see saw",
  "경찰이 나타남": "police appear appearing",
  "의사를 만남": "doctor meet meeting",
  "도둑이 듦": "thief enter entering",
  "도둑을 쫓아냄": "chased drove away",
  "갇힘": "trapped locked confined",
  "감옥이 무너짐": "collapsed crumbled",
  "신랑·신부를 봄": "bride groom see saw",
  "인자한 노인": "old person elder see saw",
  "외국인과 만남": "foreigner meet meeting",
  "공항에서 떠남": "airport leave leaving",
  "높은 탑": "tower see saw",
  "옥상에 섬": "rooftop stand standing",
  "은행에 감": "bank go going",
  "낯선 호텔": "hotel enter entering",
  "고기를 먹음": "meat eat eating",
  "잘 익은 과일": "ripe juicy sweet",
  "과수원을 거닒": "orchard walked walking strolled",
  "온전한 계란": "egg whole",
  // **"alcohol"·"wine"을 뺐다** — `term_en`이 "alcohol / wine"이라 `ownTerms` 정확 일치
  // 검사가 이 낱말들을 못 걸러내고, 그러면 "wine"이라는 말만 있어도 이 의미가 공짜로
  // 1점을 받아 새 문맥("술에 취함" 등)과 동점이 났다(실측으로 확인). 상징 이름 자체를
  // 빼고 남는 낱말만 남긴다.
  "함께 술을 나눔": "share sharing toast",
  "남이 권하는 술을 받음": "offered accepted",
  "술에 취하도록 마심": "drunk intoxicated",
  "흰 우유": "milk nourish",
  "탐스러운 복숭아": "peach ripe",
  "복숭아를 먹음": "reunited reconnected reunion",
  "감을 먹음": "persimmon ate eating",
  "9가 반복": "number nine repeat",
  "8이 반복": "number eight repeat",
  "살진 소": "fat plump fattened",
  "소가 사람을 받음": "gored rammed butted charged",
  "말을 타고 빨리 달림": "fast quickly galloping swift",
  "말이 느리게 감": "slow slowly plodding",
  "물고기가 떼지어 헤엄침": "school shoal swarm many fish",
  "거북이를 잡음": "caught catching turtle",
  "단비": "rain welcome timely gentle needed",
  "궂은 비": "rain dreary gloomy dismal drizzle",
  "길에서 비를 만남": "rain road street encountered met",
  "깨진 거울": "mirror broken cracked shattered"
};
